### PR TITLE
Update tekton client and deployment to 0.25.0

### LINKED ISSUE #624: update tekton go client and deployment to 0.25 release
/kind feature

**Description:**
We need to update the tekton go client and deployment to 0.25 to support the below two features
- Embedded custom task
- Graceful Pipeline Run Termination

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

### PR DESCRIPTION
**Pull request by Tomcli**
**Which issue is resolved by this Pull Request:** 
Resolves #624 

**Description of your changes:**
- Upgrade the KFP backend Tekton go client and deployment to 0.25.0
- Update the API and dashboard for the corresponding changes
- Make Tekton deployment into a single yaml for easier upgrade experience (following the istio and argo yaml practice)

This PR aims to upgrade Tekton to 0.25.0. We are not introducing any behavioral change in this PR. Actual support for embedded custom task and graceful termination will come in a following PR that built on top of this.

Deprecation note:
- PipelineRun termination API is not backward compatible after Tekton 0.25.0

**Environment tested:**

* Python Version (use `python --version`): 3.7
* Tekton Version (use `tkn version`): 0.25.0
* Kubernetes Version (use `kubectl version`): 1.18
* OS (e.g. from `/etc/os-release`):

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention). 

- [ ] Do you want this pull request (PR) cherry-picked into the current release branch?

    [Learn more about cherry-picking updates into the release branch](https://github.com/kubeflow/pipelines/blob/master/RELEASE.md#cherry-picking-pull-requests-to-release-branch).

### CODE REVIEW

**Comment by Tomcli** [comment]
cc @Udiknedormin @rafalbigaj

**Comment by Tomcli** [comment]
cc @pugangxa

**Comment by rafalbigaj** [comment]
Thanks @Tomcli!

**Pull request merged**
