### PR TITLE
fix(frontend) fixes tasks being erroneously marked as 'skipped'

### PR DESCRIPTION
**Pull request by drewbutlerbb4**
**Which issue is resolved by this Pull Request:** 
Resolves #

**Description of your changes:**
Tasks in the runtime execution graph are being erroneously marked as `Skipped`. This happens when task1 has a dependency on task2 and task3 and task2 has completed and task3 has not completed yet.

**Environment tested:**

* Python Version (use `python --version`):
* Tekton Version (use `tkn version`): 0.16.3
* Kubernetes Version (use `kubectl version`):
* OS (e.g. from `/etc/os-release`):

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention). 

   PR titles examples:
    * `fix(frontend): fixes empty page. Fixes #1234`
       Use `fix` to indicate that this PR fixes a bug.
    * `feat(backend): configurable service account. Fixes #1234, fixes #1235`
       Use `feat` to indicate that this PR adds a new feature. 
    * `chore: set up changelog generation tools`
       Use `chore` to indicate that this PR makes some changes that users don't need to know.
    * `test: fix CI failure. Part of #1234`
        Use `part of` to indicate that a PR is working on an issue, but shouldn't close the issue when merged.

- [ ] Do you want this pull request (PR) cherry-picked into the current release branch?
    
    If yes, use one of the following options:
  
    * **(Recommended.)** Ask the PR approver to add the `cherrypick-approved` label to this PR. The release manager adds this PR to the release branch in a batch update.
    *  After this PR is merged, create a cherry-pick PR to add these changes to the release branch. (For more information about creating a cherry-pick PR, see the [Kubeflow Pipelines release guide](https://github.com/kubeflow/pipelines/blob/master/RELEASE.md#option--git-cherry-pick).)

### CODE REVIEW

**Comment by drewbutlerbb4** [comment]
One question to @jinchihe @fenglixa, for the anySequencer, in the event that all of the dependencies of the anySequencer fail should we mark the task that depends on the anySequencer as skipped? Currently the last task does not display as shown below.

Screen Shot 2021-01-06 at 2 24 06 PM

**Comment by Tomcli** [comment]
> One question to @jinchihe @fenglixa, for the anySequencer, in the event that all of the dependencies of the anySequencer fail should we mark the task that depends on the anySequencer as skipped? This way it would show up in the runtime execution graph, whereas currently the last task in this scenario does not display as shown below ([the example pipeline used](https://github.com/drewbutlerbb4/kfp-tekton/blob/sequencer-bug-example/sdk/python/tests/compiler/testdata/any_sequencer_bug.yaml)).
> 
> Screen Shot 2021-01-06 at 2 24 06 PM

@jinchihe @fenglixa I'm not sure how anySequencer suppose to behave in datastage for the failure scenario, but currently the `anySequencer` container will keep running until it sees a succeeded task or seeing no events for 10 minutes. Should we add some way to fail fast if all the tasks are failed?

**Comment by Tomcli** [comment]
Posted the issue for the anySequencer use case. The regular whenExpression case looks good to me.
/unhold

**Pull request merged**
