### PR TITLE
fix(sdk): Verify binary data in step copy-results-artifacts. Fixes #984

### LINKED ISSUE #984: Passing small binary files with OutputPath prevents KFP to update run status
/kind bug

**What steps did you take and what happened:**

As a new user to KF I tried to write a pure python implementation of this example: https://www.kubeflow.org/docs/components/pipelines/sdk/build-pipeline/#design-your-pipeline

```
import kfp
from kfp_tekton.compiler import TektonCompiler
import kfp.components as comp

def download(url: str, data_path: comp.OutputPath('Tarball')):
    import urllib.request
    urllib.request.urlretrieve(url, data_path)

def merge_csv(file_path: comp.InputPath('Tarball'),
              output_csv: comp.OutputPath('CSV')):
  import glob
  import pandas as pd
  import tarfile
  from time import sleep

  tarfile.open(name=file_path, mode="r|gz").extractall('data')
  df = pd.concat(
      [pd.read_csv(csv_file, header=None)
       for csv_file in glob.glob('data/*.csv')])
  df.to_csv(output_csv, index=False, header=False)

create_step_merge_csv = kfp.components.create_component_from_func(
    func=merge_csv,
    base_image='python:3.7',
    packages_to_install=['pandas==1.1.4'])

web_downloader_op = kfp.components.create_component_from_func(
    func=download,
    base_image='python:3.7')

def my_pipeline(url):
  web_downloader_task = web_downloader_op(url=url)
  merge_csv_task = create_step_merge_csv(file=web_downloader_task.outputs['data'])

if __name__ == "__main__":
    TektonCompiler().compile(my_pipeline, __file__.replace(".py", ".yaml"))

```

With the `url` parameter set to "https://storage.googleapis.com/ml-pipeline-playground/iris-csv-files.tar.gz", the pipeline appears to hang in the kubeflow UI. However, inspecting the same pipeline in the Tekton UI reveals that the pipeline did run until the end.

(BTW, with `strip_eof=true` the pipeline doesn't complete at all because the tar files is corrupted)

**What did you expect to happen:**

The KFP pipeline UI to be agree with the Tekton run status.

**Additional information:**

The problem happens because Tekton updates the pipeline run status with binary data. This causes the KFP api server to try to create an SQL statement with invalid characters in it:
```
I0704 16:20:52.142395       7 error.go:247] Error 1366: Incorrect string value: '\xEF\xBF\xBD\\u...' for column 'WorkflowRuntimeManifest' at row 1
InternalServerError: Failed to update run 3c593654-b17e-4422-82e4-eef8d582197b. error: 'Error 1366: Incorrect string value: '\xEF\xBF\xBD\\u...' for column 'WorkflowRuntimeManifest' at row 1'
github.com/kubeflow/pipelines/backend/src/common/util.NewInternalServerError
	/go/src/github.com/kubeflow/pipelines/backend/src/common/util/error.go:142
github.com/kubeflow/pipelines/backend/src/apiserver/storage.(*RunStore).UpdateRun
	/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/storage/run_store.go:434
github.com/kubeflow/pipelines/backend/src/apiserver/resource.(*ResourceManager).ReportWorkflowResource
	/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/resource/resource_manager.go:966
github.com/kubeflow/pipelines/backend/src/apiserver/server.(*ReportServer).ReportWorkflow
	/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/server/report_server.go:40
github.com/kubeflow/pipelines/backend/api/go_client._ReportService_ReportWorkflow_Handler.func1
	/go/src/github.com/kubeflow/pipelines/backend/api/go_client/report.pb.go:337
main.apiServerInterceptor
	/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/interceptor.go:30
github.com/kubeflow/pipelines/backend/api/go_client._ReportService_ReportWorkflow_Handler
	/go/src/github.com/kubeflow/pipelines/backend/api/go_client/report.pb.go:339
google.golang.org/grpc.(*Server).processUnaryRPC
	/go/pkg/mod/google.golang.org/grpc@v1.41.0/server.go:1279
google.golang.org/grpc.(*Server).handleStream
	/go/pkg/mod/google.golang.org/grpc@v1.41.0/server.go:1608
google.golang.org/grpc.(*Server).serveStreams.func1.2
	/go/pkg/mod/google.golang.org/grpc@v1.41.0/server.go:923
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1357
Failed to update the run.
```

**Environment:**

* SDK Version: 1.2.1

### PR DESCRIPTION
**Pull request by maxdebayser**
**Which issue is resolved by this Pull Request:** 
Resolves  #984

**Description of your changes:**

Add a verification to copy-results-artifacts to prevent small binary files from being copied. The presence of unprintable characters in the PipelineRun status breaks the `UpdateRun` function in `run_store.go` 

The verification with awk is compatible with the busybox container.

**Environment tested:**

* Python Version (use `python --version`): 3.8
* Tekton Version (use `tkn version`): 1.5
* Kubernetes Version (use `kubectl version`):  v1.23.5
* OS (e.g. from `/etc/os-release`):  Fedora 35

### CODE REVIEW

**Comment by Tomcli** [comment]
Hi @maxdebayser, can your run `make unit_test GENERATE_GOLDEN_YAML=True` with the new python sdk code to regenerate the unit test yaml? So it can pass our github action tests

**Comment by Tomcli** [comment]
/lgtm
@maxdebayser once you signed the cla, please let me know so I can retrigger the cla check.

**Comment by Tomcli** [comment]
@maxdebayser based on https://github.com/kubeflow/kfp-tekton/pull/985/checks?check_run_id=7219006673
Seems like one of your commit is not using the email with signed CLA. Maybe you can squash your commits into one?

**Comment by maxdebayser** [comment]
@Tomcli I've verified that my IBM e-mail address is set in my commits. I've also added my IBM e-mail as a secondary to may github.com account. And now I've also clicked on "New Contributors: Update this check after signing the CLA by clicking [here]" link in the CLA check message. Apparently it's passing now.

**Comment by Tomcli** [comment]
thanks @maxdebayser 
/approve

**Pull request merged**
