### PR TITLE
fix(sdk): Address default pipeline timeout behavior

### LINKED ISSUE #352: Disabling pipeline timeout doesn't work
/kind bug

**What steps did you take and what happened:**
Disabling pipeline timeout should be possible by setting the timeout to 0. However, setting the timeout to 0 currently doesn't create the timeout field in Tekton YAML and therefore the default (60m) is used.

**What did you expect to happen:**
`dsl.get_pipeline_conf().set_timeout(0)` should be supported so that the generated Tekton YAML explicitly contains `timeout: 0`.

**Additional information:**
I believe the issue comes from https://github.com/kubeflow/kfp-tekton/blob/033161415d7ed52aeb3660b406368a91485d3b28/sdk/python/kfp_tekton/compiler/compiler.py#L175 which should be checking for `None` instead.

### PR DESCRIPTION
**Pull request by Tomcli**
**Which issue is resolved by this Pull Request:** 
Resolves #352 

**Description of your changes:**
Update the pipeline to not timeout by default in order to align with the Argo behavior. 

**Environment tested:**

* Python Version (use `python --version`): 3.7
* Tekton Version (use `tkn version`): 0.14
* Kubernetes Version (use `kubectl version`): 1.16
* OS (e.g. from `/etc/os-release`):

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention). 

   PR titles examples:
    * `fix(frontend): fixes empty page. Fixes #1234`
       Use `fix` to indicate that this PR fixes a bug.
    * `feat(backend): configurable service account. Fixes #1234, fixes #1235`
       Use `feat` to indicate that this PR adds a new feature. 
    * `chore: set up changelog generation tools`
       Use `chore` to indicate that this PR makes some changes that users don't need to know.
    * `test: fix CI failure. Part of #1234`
        Use `part of` to indicate that a PR is working on an issue, but shouldn't close the issue when merged.

- [ ] Do you want this pull request (PR) cherry-picked into the current release branch?
    
    If yes, use one of the following options:
  
    * **(Recommended.)** Ask the PR approver to add the `cherrypick-approved` label to this PR. The release manager adds this PR to the release branch in a batch update.
    *  After this PR is merged, create a cherry-pick PR to add these changes to the release branch. (For more information about creating a cherry-pick PR, see the [Kubeflow Pipelines release guide](https://github.com/kubeflow/pipelines/blob/master/RELEASE.md#option--git-cherry-pick).)

### CODE REVIEW

**Comment by Tomcli** [comment]
So I make all the pipelines to not timeout by default. @jfigura does this address your issue?

**Comment by jfigura** [comment]
Yes, thanks @Tomcli !

**Comment by drewbutlerbb4** [comment]
Thanks @Tomcli, we should probably add this change as a section `timeout for tasks and pipelines section` in the [custom Tekton implementation](https://github.com/kubeflow/kfp-tekton/blob/master/sdk/FEATURES.md#pipeline-dsl-features-with-a-custom-tekton-implementation) of the features docs since this goes against the [default global timeout](https://github.com/tektoncd/pipeline/blob/8f5feedb95f71b7dc5a6cb247ea1e3e8fdff7191/docs/taskruns.md#configuring-the-failure-timeout) Tekton implementation.

**Comment by Tomcli** [comment]
> Thanks @Tomcli, we should probably add this change as a section `timeout for tasks and pipelines section` in the [custom Tekton implementation](https://github.com/kubeflow/kfp-tekton/blob/master/sdk/FEATURES.md#pipeline-dsl-features-with-a-custom-tekton-implementation) of the features docs since this goes against the [default global timeout](https://github.com/tektoncd/pipeline/blob/8f5feedb95f71b7dc5a6cb247ea1e3e8fdff7191/docs/taskruns.md#configuring-the-failure-timeout) Tekton implementation.

Done, also added a flag for those who want to switch to the Tekton default behavior.

**Comment by drewbutlerbb4** [comment]
Great
/lgtm

**Pull request merged**
