### PR TITLE
`chore(sdk) Bump kfp dependency to 1.8.13`

### LINKED ISSUE #998: Bump kfp dependency to latest 1.8.13
/kind feature

**Description:**
Bump kfp dependency to 1.8.13. This resolves a number of issues where downstream projects require typing extensions > 4.

**Additional information:**
See add info.
https://github.com/kubeflow/pipelines/issues/7983
https://github.com/elyra-ai/elyra/issues/2816

### PR DESCRIPTION
**Pull request by akchinSTC**
**Which issue is resolved by this Pull Request:** 
Resolves #998

**Description of your changes:**
Update kfp dependency to latest fixpack version

**Environment tested:**

* Python Version (use `python --version`):
* 3.8
* Tekton Version (use `tkn version`):
* Kubernetes Version (use `kubectl version`):
* OS (e.g. from `/etc/os-release`):

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by Tomcli** [comment]
@akchinSTC do you need us to cut a kfp-tekton minor release (v1.2.3) so you can use it on pypi and conda?

**Comment by akchinSTC** [comment]
> @akchinSTC do you need us to cut a kfp-tekton minor release (v1.2.3) so you can use it on pypi and conda?
that would be awesome

**Comment by Tomcli** [comment]
/lgtm
/approve
will do a follow up pr to cut the minor SDK release.

**Pull request merged**
