### PR TITLE
chore: Objectstore package refactoring.

### LINKED ISSUE #877: Investigate can objectstorelogger package utilizes the new objectstore package
Thanks @ScrapCodes. Functionality wise it looks good to me. I'm thinking can the `objectstorelogger` package also be use this new package? In our implementation with Taskrun, both logs and artifacts are pushed to same path. The only exception is that the log file is not compressed. This way we can reduce the number of packages need to import for each controller. What do you think?

It can be a separate PR from this. I will merge this PR for now and open an new issue.

_Originally posted by @Tomcli in https://github.com/kubeflow/kfp-tekton/issues/876#issuecomment-1068551152_

### PR DESCRIPTION
**Pull request by ScrapCodes**
**Which issue is resolved by this Pull Request:** 
Resolves #877

**Description of your changes:**

Now object store logger uses the object store package and both are combined into a single package.

**Environment tested:**
IBM Cloud, logging to COS.

* Python Version (use `python --version`):
* Tekton Version (use `tkn version`):
* Kubernetes Version (use `kubectl version`):
* OS (e.g. from `/etc/os-release`):

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by Tomcli** [comment]
thanks @ScrapCodes 
/lgtm

**Comment by yhwang** [comment]
this causes go panic:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x9e8c3e]

goroutine 1 [running]:
github.com/kubeflow/kfp-tekton/tekton-catalog/objectstore/pkg/writer.(*Logger).load(0xc0001e8180, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/artifacts/tekton-catalog/objectstore/pkg/writer/objectstorelogger.go:95 +0x2be
github.com/kubeflow/kfp-tekton/tekton-catalog/objectstore/pkg/writer.(*Logger).LoadDefaults(0xc0001e8180, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/artifacts/tekton-catalog/objectstore/pkg/writer/objectstorelogger.go:121 +0x65
github.com/kubeflow/kfp-tekton/tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun.initLogger(0x24d9420, 0xc000850210, 0x7f2719932ed0, 0xc0007ecdc0, 0x100000006)
	/artifacts/tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/controller.go:132 +0xa38
github.com/kubeflow/kfp-tekton/tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun.NewController.func1(0x24d9420, 0xc000850210, 0x249d820, 0xc00001e120, 0xc000632000)
	/artifacts/tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/controller.go:181 +0x1bf
knative.dev/pkg/injection/sharedmain.ControllersAndWebhooksFromCtors(0x24d9420, 0xc000850210, 0xc00001e120, 0xc00098ff70, 0x1, 0x1, 0x1, 0x37e11d600, 0x2540be400, 0x77359400, ...)
	/root/go/pkg/mod/knative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/injection/sharedmain/main.go:350 +0x183
knative.dev/pkg/injection/sharedmain.MainWithConfig(0x24d9420, 0xc0007a6990, 0x21a9c9b, 0x17, 0xc0007e4240, 0xc00098ff70, 0x1, 0x1)
	/root/go/pkg/mod/knative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/injection/sharedmain/main.go:192 +0x62c
knative.dev/pkg/injection/sharedmain.MainWithContext(0x24d9420, 0xc0007a6990, 0x21a9c9b, 0x17, 0xc00083ff70, 0x1, 0x1)
	/root/go/pkg/mod/knative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/injection/sharedmain/main.go:131 +0xda
main.main()
	/artifacts/tekton-catalog/pipeline-loops/cmd/controller/main.go:40 +0x1b9
```

**Comment by ScrapCodes** [comment]
My bad, I missed a commit in this PR.

**Comment by ScrapCodes** [comment]
@yhwang #887 should fix this.

**Pull request merged**
