### PR TITLE
Optimize kfp-tekon SDK compile time

### LINKED ISSUE #735: Optimize kfp-tekton SDK compile time
/kind feature

**Description:**
When compiling the flip coin example, it takes around 0.25s to compile the pipeline DSL to Tekton yaml which is not very ideal for our internal users. So we want to optimize the compile time as much as possible.

On the initial testing, most of the bottlenecks are coming from loading/writing the dictionary into yaml/json. Thus we want to reduce those steps as much as possible 

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

### PR DESCRIPTION
**Pull request by Tomcli**
**Which issue is resolved by this Pull Request:** 
Resolves #735 

**Description of your changes:**
Reduce the number of writing and loading into YAML/JSON during compile time. This should reduce the compile time for 0.08-0.1s. 

E.g. The flip-coin example is reduced from 0.25s to 0.13s. 

**Environment tested:**

* Python Version (use `python --version`):
* Tekton Version (use `tkn version`):
* Kubernetes Version (use `kubectl version`):
* OS (e.g. from `/etc/os-release`):

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by Tomcli** [comment]
cc @Udiknedormin

**Comment by Udiknedormin** [comment]
@Tomcli My benchmark shows that a minimal example compiles TWICE as fast now --- more than enough of an optimisation as for now.

**Comment by Udiknedormin** [comment]
@Tomcli

One thing comes to mind: I noticed that `_write_workflow` has the ability to simply return the yaml in-memory:
```python
if package_path is None:
  return yaml_text
```
However, `_create_and_write_workflow` doesn't propagate that, as it doesn't return the `_write_workflow`'s result. In the original KFP it wasn't a real issue, as the implementation of `_create_and_write_workflow` was as simple as:
```python
workflow = self._create_workflow(
    pipeline_func,
    pipeline_name,
    pipeline_description,
    params_list,
    pipeline_conf)
self._write_workflow(workflow, package_path)
_validate_workflow(workflow)
```
so one could simply use `_create_workflow` if really needed. It's to as easy for kfp-tekton, `_create_and_write_workflow` being 60 lines.

If either `compile` with `package_path=None` would be supported, or another method that would return a yaml (or maybe a list of yamls, considering the possibility of multiple resources?) in-memory --- that would probably result in an even bigger speed-up.

**Comment by Tomcli** [comment]
> ```python
> _write_workflow(
> ```

For the new method, I will create it in a separate PR that returns the workflow dictionary since the bottlenecks are happening in yaml.load/dump.

**Comment by Tomcli** [comment]
@yhwang can you lgtm this PR? thanks.

**Pull request merged**
