### PR TITLE
Code clean up and refactor

### LINKED ISSUE #96: Refactor compiler and op to template function.
/kind feature

**Description:**
[A clear and concise description of what your proposal. What problem does it solve?]
As we introduce more features, there are some task/step template that we have to introduce in order to replicate some actions in the Argo sidecar. So we should refactor the code in a way that any additional template can be added as a plugin function.

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

### PR DESCRIPTION
**Pull request by Tomcli**
**Which issue is resolved by this Pull Request:** 
Resolves #96 

**Description of your changes:**
Break down some functions into smaller piece and clean up some old code.

**Environment tested:**

* Python Version (use `python --version`):
* Tekton Version (use `tkn version`):
* Kubernetes Version (use `kubectl version`):
* OS (e.g. from `/etc/os-release`):

### CODE REVIEW

**Comment by ckadner** [comment]
Sorry, jumped the gun a bit. Let @Tomcli unhold it first :-)

**Comment by Tomcli** [comment]
Thanks @ckadner, maybe you can review the input artifact implementation first? https://github.com/kubeflow/kfp-tekton/pull/104

or I can merge those 2 into a single pr if you think is not too much to review.

**Comment by ckadner** [comment]
> Thanks @ckadner, maybe you can review the input artifact implementation first? #104
> 
> or I can merge those 2 into a single pr if you think is not too much to review.

Up to you, I looked at both PRs and both look good.

**Comment by ckadner** [comment]
`_op_to_template.py` needs to be rebased now that #104 is merged

**Pull request merged**
