### PR TITLE
Feature branch for moving to Tekton 0.16

### LINKED ISSUE #304: update to tekton 0.16 for next release
/kind feature

**Description:**
Tekton 0.16 introduced several features that can unblock some of our older issues
- more context variables such as pipeline uid (unblock https://github.com/kubeflow/kfp-tekton/issues/78)
- TaskSpec metadata, useful for distinguish task generated by kfp vs tfx
- variable substitution works on configmap and secrets
- WhenExpressions (new beta api for conditional)

Deprecation note:
- conditional v1alpha1 is deprecated
- PipelineRun.Spec.ServiceAccountNames is being deprecated in favor of PipelineRun.Spec.TaskRunSpec[].ServiceAccountName

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

### PR DESCRIPTION
**Pull request by Tomcli**
**Which issue is resolved by this Pull Request:** 
Resolves #304 

**These features will break backward compatibility, need to wait for Openshift pipeline to support Tekton 0.16 before merging.**

related tasks: 
- [x] #258 #310 when adding beta whenExpression support - UI PR #328 
   - The new conditions are now in its own "task" to replicate how Argo defines their conditions in its own Argo "template". Please check the FEATURE readme and [argo condition example](https://github.com/kubeflow/pipelines/blob/master/sdk/python/tests/compiler/testdata/coin.yaml) for more details.
- [x] #78 when adding more context variables
   - List of new supported variables:
      ```
      argo -> tekton
      {{workflow.uid}} -> $(context.pipelineRun.uid)
      {{workflow.name}} -> $(context.pipelineRun.name)
      {{workflow.namespace}} -> $(context.pipelineRun.namespace)
      {{workflow.parameters.%s}} -> $(params.%s)
      ```
- [x]  Add task wise metadata, enabled component.yaml template information.

**Description of your changes:**
This is an experimental feature branch for some tekton 0.16 features. We will only merge these features when OKD openshift pipeline supports Tekton 0.16+

**Environment tested:**

* Python Version (use `python --version`): 3.7
* Tekton Version (use `tkn version`): 0.16.3
* Kubernetes Version (use `kubectl version`): 1.17
* OS (e.g. from `/etc/os-release`):

### CODE REVIEW

**Review by drewbutlerbb4 — CHANGES_REQUESTED** [review]

**Comment by drewbutlerbb4** [comment]
I have a few comments for the conditions.

Also in `_group_to_dag_template` of `sdk/python/kfp_tekton/compiler/compiler.py` 
I believe we can remove 
```      'apiVersion': tekton_api_version,```
from the template since it is no longer used.

**Comment by Tomcli** [comment]
Openshift pipeline 0.16 is available in open source, need to check which IKS openshift is supporting this version.

**Comment by Tomcli** [comment]
@ckadner do you have any comment on this PR? If not we can merge it to master since this PR has been rebased multiple times.

**Comment by ckadner** [comment]
> @ckadner do you have any comment on this PR? If not we can merge it to master since this PR has been rebased multiple times.

I think this looks okay. But I see changes from other merged PRs in your PR. Did you try to rebase your PR instead of merging those changes into you PR

**Comment by Tomcli** [comment]
> > @ckadner do you have any comment on this PR? If not we can merge it to master since this PR has been rebased multiple times.
> 
> I think this looks okay. But I see changes from other merged PRs in your PR. Did you try to rebase your PR instead of merging those changes into you PR

At some point there were too many conflicts to rebase on each commit, so I ended up with merging it and solve all the conflicts in a single batch.

**Review by ckadner — APPROVED** [review]
/lgtm

**Comment by Tomcli** [comment]
if there's no more objection i will unhold this PR tomorrow morning.

**Pull request merged**
