### PR TITLE
backend(chore): update backend to tekton 0.50

### PR DESCRIPTION
**Pull request by Tomcli**
**Which issue is resolved by this Pull Request:** 
Part of #1308 

**Description of your changes:**

**Environment tested:**

* Python Version (use `python --version`):
* Tekton Version (use `tkn version`):
* Kubernetes Version (use `kubectl version`):
* OS (e.g. from `/etc/os-release`):

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by Tomcli** [comment]
e2e test passed, it really seems like github action is running out of resources. Let me open another PR to fix the github action issue.
https://cloud.ibm.com/devops/pipelines/tekton/f85a45d2-36fc-45fb-a449-b01c13cf5191/runs/524e0e05-8891-4aab-9373-bc25c4b429e8/e2e-test-many-edges/run-test?env_id=ibm:yp:us-south&retry=0

**Comment by Tomcli** [comment]
e2e test passed. All the status and childreference type are all in v1 API only since Tekton 0.50 marked v1beta1 as deprecated. https://cloud.ibm.com/devops/pipelines/tekton/f85a45d2-36fc-45fb-a449-b01c13cf5191/runs/be0ca66e-322b-433a-b617-0c8693d8c958?env_id=ibm:yp:us-south

**Comment by Tomcli** [comment]
Cache server is updated to handle Tekton v1 api resource reference to pass CI. Will migrate everything to v1 in a following PR.

**Review by yhwang — APPROVED** [review]
/lgtm

**Pull request merged**
