### PR TITLE
chore(release): Add 1.4.1 release patch

### PR DESCRIPTION
**Pull request by Tomcli**
**Which issue is resolved by this Pull Request:** 
Resolves #

**Description of your changes:**
Add 1.4.1 release patch for the recent sdk and backend bug fixes. SDK release will be 1.4.2

**Environment tested:**

* Python Version (use `python --version`):
* Tekton Version (use `tkn version`):
* Kubernetes Version (use `kubectl version`):
* OS (e.g. from `/etc/os-release`):

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by yhwang** [comment]
so most of the images are using 1.4.1 tag, but only kubectl-wrapper is using 1.4.2. and the kfp-tekton is also 1.4.2.
is there a way to sync up those versions again? I believe it would be good if they all use the same version tag.

**Comment by Tomcli** [comment]
> so most of the images are using 1.4.1 tag, but only kubectl-wrapper is using 1.4.2. and the kfp-tekton python package is also 1.4.2. is there a way to sync up those versions again? I believe it would be good if they all use the same version tag.

I probably can change that image to latest since we are not updating this image very often. The SDK and backend can have different release based on the need.

**Comment by Tomcli** [comment]
The e2e run passed with new version tag https://cloud.ibm.com/devops/pipelines/tekton/f85a45d2-36fc-45fb-a449-b01c13cf5191/runs/5beb9ee4-02f7-4540-9194-cabe80258c53/test/run-go-unittests?env_id=ibm:yp:us-south

**Review by yhwang — APPROVED** [review]
/lgtm

**Pull request merged**
