### PR TITLE
Enhance Any Sequencer to support watching run

### PR DESCRIPTION
**Pull request by jinchihe**
**Which issue is resolved by this Pull Request:** 
Resolves #

**Description of your changes:**
Currently the Any Sequencer support watching taskrun and conditions, do not support watching run, the PR is going to support that.

**Environment tested:**

* Python Version (use `python --version`):
* Tekton Version (use `tkn version`):
* Kubernetes Version (use `kubectl version`):
* OS (e.g. from `/etc/os-release`):

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention). 

- [ ] Do you want this pull request (PR) cherry-picked into the current release branch?

    [Learn more about cherry-picking updates into the release branch](https://github.com/kubeflow/pipelines/blob/master/RELEASE.md#cherry-picking-pull-requests-to-release-branch).

### CODE REVIEW

**Comment by jinchihe** [comment]
@vincent-pli @fenglixa Would you please help to review? Great thanks!

**Review by vincent-pli — COMMENTED** [review]
Thanks @jinchihe , looks good.

**Comment by pugangxa** [comment]
/lgtm
Thanks Jinchi.

**Pull request merged**
