### PR TITLE
feat(backend): handle pipelineloop status

### PR DESCRIPTION
**Pull request by yhwang**
**Description of your changes:**

When using `embedded-status: minimal`, the nested pipelineloop status
is missing. Add logic in persistence agent to retrieve runs and taskruns
statuses for nested pipelineloop.

Signed-off-by: Yihong Wang <yh.wang@ibm.com>

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by yhwang** [comment]
rebased and forced-pushed.

**Comment by yhwang** [comment]
[status.json.zip](https://github.com/kubeflow/kfp-tekton/files/9441587/status.json.zip)
attached a status JSON, the status portion of a RunDetails retrieving from the backend API. You can find `childReferences` and also the corresponding taskruns/runs statuses next to those childReferences.

**Comment by yhwang** [comment]
add an env var to pass a list of kinds that contains childReferences in extraFields. persistence agent retrieves taskruns/runs status for those childReferences and embed their statuses next to childReferences.

**Comment by Tomcli** [comment]
@yhwang Just a quick question, does it also work with tekton finally? e.g. https://github.com/kubeflow/kfp-tekton/blob/master/sdk/python/tests/compiler/testdata/exit_handler.yaml

**Comment by yhwang** [comment]
here is the status output of the exit-handler: 
[exit-handler-status.json.zip](https://github.com/kubeflow/kfp-tekton/files/9472081/exit-handler-status.json.zip)
all taskruns/runs are listed in the childReferences, including those in finally. so no extra handler for those taskruns/runs in finally.

**Comment by yhwang** [comment]
for Run, as long as the childReferences is under `extraFields.pipelineRuns.*.status.childReferences`. persistent agent can look up those taskruns/runs and retrieve their status outputs and embed them next to `childReferences`

The usage is to put those Runs' kinds into the new env, i.e. `PipelineRun,Exception` (using comma as separator).

**Comment by Tomcli** [comment]
thanks @yhwang 
/lgtm
/approve

**Pull request merged**
