### PR TITLE
Generate long_description for PyPi from sdk/README.md

### LINKED ISSUE #185: Generate long_description for PyPi based on sdk/README.md
/kind feature

**Description:**
PyPi uses the `long_description` from `setup.py` for the documentation of the landing page of the [`kfp-tekton` project on PyPi.org](https://pypi.org/project/kfp-tekton/).

We should use the content of our `sdk/README.md` for that `long_description`.

```Python
import setuptools

with open("sdk/README.md", "r") as f:
    long_description = f.read()
    # TODO: replace relative links with absolute links

setuptools.setup(
    name="...",
    description="...",
    long_description=long_description,
    long_description_content_type="text/markdown",
    # ...
)
```
/cc @jinchihe 
/assign

### PR DESCRIPTION
**Pull request by ckadner**
**Which issue is resolved by this Pull Request:** 
Resolves #185

**Description of your changes:**
- Modify `setup.py` to read `long_description` from [`sdk/README.md`](https://github.com/kubeflow/kfp-tekton/blob/master/sdk/README.md)
- Replace relative links with absolute links to `kfp-tekton` GitHub repo
- Add anchor tags around headings for document-internal links from TOC
- Add `make distribution` target for upload to `testpypi`

**Updated SDK README:**
> [sdk/README.md](https://github.com/ckadner/kfp-tekton/blob/PyPi_description_from_Github_README/sdk/README.md)

**Result on Test-PyPi:**
> https://test.pypi.org/project/kfp-tekton/0.1.0rc5/

**Environment tested:**
* Python Version (use `python --version`): `3.7.5`
* Tekton Version (use `tkn version`): `0.13.0`
* Kubernetes Version (use `kubectl version`): `0.16`
* OS (e.g. from `/etc/os-release`): Mac OS

/cc @jinchihe @animeshsingh

### CODE REVIEW

**Comment by animeshsingh** [comment]
thanks @ckadner - where is the SDK referenced in README?

**Comment by ckadner** [comment]
> thanks @ckadner - where is the SDK referenced in README?

@animeshsingh -- sorry, can you elaborate on your question?

**Comment by ckadner** [comment]
@animeshsingh -- I updated the `sdk/README.md` with an extra section that explains how to install from PyPi vs install from source:

**Updated SDK README:**
> [sdk/README.md](https://github.com/ckadner/kfp-tekton/blob/PyPi_description_from_Github_README/sdk/README.md)

**Result on Test-PyPi:**
> https://test.pypi.org/project/kfp-tekton/0.1.0rc5/

**Comment by Tomcli** [comment]
Approve this PR first since we need to cut the pypi release note before the pipelinerun changes.
/lgtm
/approve

**Comment by ckadner** [comment]
Thanks @Tomcli 

`kfp-tekton` on PyPi: https://pypi.org/project/kfp-tekton/0.1.0/

**Pull request merged**
