### PR TITLE
updated titanic-ml generated with kale 0.5.1

### PR DESCRIPTION
**Pull request by animeshsingh**
updated .py file with latest kale 0.5.1
currently won't compile with kfp-tekton 0.3 sdk

### CODE REVIEW

**Comment by Tomcli** [comment]
@animeshsingh Same errors as in Kale 0.5.0 when running with KFP 1.0 SDK using Argo.
```
Traceback (most recent call last):
  File "titanic-ml.py", line 988, in <module>
    compiler.Compiler().compile(pipeline_func, pipeline_filename)
  File "/Users/tommyli/anaconda2/envs/py3/lib/python3.7/site-packages/kfp/compiler/compiler.py", line 905, in compile
    package_path=package_path)
  File "/Users/tommyli/anaconda2/envs/py3/lib/python3.7/site-packages/kfp/compiler/compiler.py", line 962, in _create_and_write_workflow
    _validate_workflow(workflow)
  File "/Users/tommyli/anaconda2/envs/py3/lib/python3.7/site-packages/kfp/compiler/compiler.py", line 989, in _validate_workflow
    Error: {}'''.format(result.stderr.decode('utf-8'))
RuntimeError: Internal compiler error: Compiler has produced Argo-incompatible workflow.
Please create a new issue at https://github.com/kubeflow/pipelines/issues attaching the pipeline code and the pipeline package.
Error: time="2020-10-12T16:46:26-07:00" level=fatal msg="/dev/stdin failed to parse: error unmarshaling JSON: while decoding JSON: json: unknown field \"volumes\""
```

**Comment by Tomcli** [comment]
To reproduce it, run 
```
pip install kfp==1.0.0
pip install kubeflow-kale --upgrade
python samples/titanic-ml-dataset/titanic-ml.py
```

**Comment by Tomcli** [comment]
I also tried kfp 1.0.1 and still the same error

**Comment by animeshsingh** [comment]
@Tomcli as discussed, please relay the changes needed to be made to the .py file for it to work with kfp-tekton

**Comment by animeshsingh** [comment]
@Tomcli can you suggest changes in the .py file where path needs to be changed?

**Comment by Tomcli** [comment]
@googlebot I consent.

**Pull request merged**
