### PR TITLE
Allow a custom image for the step

### PR DESCRIPTION
**Pull request by diegolovison**
**Which issue is resolved by this Pull Request:** 
Resolves https://github.com/kubeflow/kfp-tekton/issues/1316

**Description of your changes:**
Allow a custom image for the step

**Environment tested:**

* Python Version (use `python --version`):
* Tekton Version (use `tkn version`):
* Kubernetes Version (use `kubectl version`):
* OS (e.g. from `/etc/os-release`):

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by Tomcli** [comment]
Hi @diegolovison, I think this feature is implemented in the kfp-tekton 1.7.1 release. If you want this features on 1.5, I can try to cherry pick this change and cut a new 1.5 release
https://github.com/kubeflow/kfp-tekton/pull/1265

**Comment by diegolovison** [comment]
Sounds good because it is what we support this time.

**Comment by diegolovison** [comment]
Also, if you could generate a build after that :)

**Comment by Tomcli** [comment]
> Sounds good because it is what we support. Also, if you could generate a build after that :)

You mean a Pypi build right? We will update the Pypi release as well after the integration test and release is done.

**Comment by diegolovison** [comment]
Yeap. Thanks

**Comment by diegolovison** [comment]
https://github.com/kubeflow/kfp-tekton/commit/17a9022a8ed194728a05f012a7b27b95f7802a89
https://github.com/kubeflow/kfp-tekton/commit/6081024172f61fc9ea8ec8a095eecdc37486cfe5

**Pull request closed without merging**
