### PR TITLE
fix: PipelineLoop nested validation logic fixed.

### LINKED ISSUE #637: PipelineLoop controller cannot handle nested inline custom task
/kind bug

**What steps did you take and what happened:**
The current PipelineLoop controller can handle inline custom taskSpec on the first layer. However, for the inline taskSpec in the nested layer, it's still expecting the old client behavior.

```
PipelineLoop kubeflow/withitem-multiple-nesting-pipeline-0f753-withitem-multipl-hkmtz can't be Run; it has an invalid spec: missing field(s): spec.pipelineSpec.tasks[2].taskSpec.steps
```

We need to fix this and let all the nested spec to follow the new Tekton v0.25 API.

**What did you expect to happen:**

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

* Python Version (use `python --version`):
* SDK Version: 
* Tekton Version (use `tkn version`):
* Kubernetes Version (use `kubectl version`):
* OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by ScrapCodes**
Added missing enablement of feature-flag enable-custom-task.
Also added nested task validation.

**Which issue is resolved by this Pull Request:** 
Resolves #637 

**Description of your changes:**

**Environment tested:**

* Python Version (use `python --version`):
* Tekton Version (use `tkn version`):
* Kubernetes Version (use `kubectl version`):
* OS (e.g. from `/etc/os-release`):

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention). 

- [ ] Do you want this pull request (PR) cherry-picked into the current release branch?

    [Learn more about cherry-picking updates into the release branch](https://github.com/kubeflow/pipelines/blob/master/RELEASE.md#cherry-picking-pull-requests-to-release-branch).

### CODE REVIEW

**Comment by ScrapCodes** [comment]
I am getting a different error:
```
{"level":"error","ts":"2021-06-25T15:15:48.619Z","logger":"pipelineloop-controller","caller":"controller/controller.go:548","msg":"Reconcile error","knative.dev/controller":"github.com.kubeflow.kfp-tekton.tekton-catalog.pipeline-loops.pkg.reconciler.pipelinelooprun.Reconciler","knative.dev/kind":"tekton.dev.Run","duration":0.169647362,"error":"1 error occurred:\n\t* error creating PipelineRun from Run pr-loop-example-loop-task-qdgxr: admission webhook \"webhook.pipeline.tekton.dev\" denied the request: mutation failed: cannot decode incoming new object: json: unknown field \"spec\"\n\n","stacktrace":"knative.dev/pkg/controller.(*Impl).handleErr\n\tknative.dev/pkg@v0.0.0-20210331065221-952fdd90dbb0/controller/controller.go:548\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20210331065221-952fdd90dbb0/controller/controller.go:531\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\tknative.dev/pkg@v0.0.0-20210331065221-952fdd90dbb0/controller/controller.go:468"}
```

**Comment by Tomcli** [comment]
@ScrapCodes I'm still getting this error from your example
```
{"level":"info","ts":"2021-06-25T17:07:14.058Z","logger":"pipelineloop-controller.event-broadcaster","caller":"record/event.go:282","msg":"Event(v1.ObjectReference{Kind:\"Run\", Namespace:\"default\", Name:\"pr-loop-example-loop-task-twnjn\", UID:\"81902555-3930-4f49-b339-55802d7dc877\", APIVersion:\"tekton.dev/v1alpha1\", ResourceVersion:\"42311078\", FieldPath:\"\"}): type: 'Warning' reason: 'Failed' PipelineLoop default/pr-loop-example-loop-task-twnjn can't be Run; it has an invalid spec: missing field(s): spec.pipelineSpec.tasks[1].taskSpec.steps"}
```

I think the error you have is due to some bad decoding in the inlined JSON? Let me also add few more debug messages to see can I find out the error.

**Comment by Tomcli** [comment]
I'm able to make nested loop working after applying your new context to the reconciler
https://github.com/ScrapCodes/kfp-tekton/pull/2

If you can add a unit test for the `enableCustomTaskFeatureFlag` function and apply it to the reconciler, then this PR should be good to go.

**Comment by ScrapCodes** [comment]
@googlebot I consent.

**Comment by Tomcli** [comment]
@googlebot I consent.

**Comment by Tomcli** [comment]
I think some tests are broken when upgrading to Tekton 0.25, but the functionality for this PR is not effected. I will open another issue to fix the tests. For now I will merge this PR to move the inline spec forward.

**Pull request merged**
