### PR TITLE
Fix the yaml cannot show in Safari browser issue

### LINKED ISSUE #364: Yaml file cannot show with Safari browser
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Yaml file cannot show with Safari browser, as below picture.
image

It's OK with my Chrome browser.

**What did you expect to happen:**
Show yaml file correctly

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

* Python Version (use `python --version`):
* SDK Version: 
* Tekton Version (use `tkn version`):
* Kubernetes Version (use `kubectl version`):
* OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by fenglixa**
**Which issue is resolved by this Pull Request:** 
Resolves #364

**Description of your changes:**
Yaml file cannot show with Safari browser
Root-Cause: react-ace Editor doesn't support in Safari when height or width is a percentage

**Environment tested:**
After fixed, both Chrome and Safari browser are OK now:
image

* Python Version (use `python --version`):
* Tekton Version (use `tkn version`):
* Kubernetes Version (use `kubectl version`):
* OS (e.g. from `/etc/os-release`):

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention). 

   PR titles examples:
    * `fix(frontend): fixes empty page. Fixes #1234`
       Use `fix` to indicate that this PR fixes a bug.
    * `feat(backend): configurable service account. Fixes #1234, fixes #1235`
       Use `feat` to indicate that this PR adds a new feature. 
    * `chore: set up changelog generation tools`
       Use `chore` to indicate that this PR makes some changes that users don't need to know.
    * `test: fix CI failure. Part of #1234`
        Use `part of` to indicate that a PR is working on an issue, but shouldn't close the issue when merged.

- [ ] Do you want this pull request (PR) cherry-picked into the current release branch?
    
    If yes, use one of the following options:
  
    * **(Recommended.)** Ask the PR approver to add the `cherrypick-approved` label to this PR. The release manager adds this PR to the release branch in a batch update.
    *  After this PR is merged, create a cherry-pick PR to add these changes to the release branch. (For more information about creating a cherry-pick PR, see the [Kubeflow Pipelines release guide](https://github.com/kubeflow/pipelines/blob/master/RELEASE.md#option--git-cherry-pick).)

### CODE REVIEW

**Comment by drewbutlerbb4** [comment]
We should probably wait for https://github.com/kubeflow/pipelines/pull/4818 to be reviewed/merged so that we align with kfp

**Comment by fenglixa** [comment]
This issue was addressed in pipeline. Ready for us now.
/unhold

**Comment by drewbutlerbb4** [comment]
/lgtm
Thanks!

**Pull request merged**
