### PR TITLE
Chore: Update readme and license headers

### PR DESCRIPTION
**Pull request by Tomcli**
**Which issue is resolved by this Pull Request:** 
Resolves #

**Description of your changes:**
Update readme and license headers with the latest documentations. Also remove deprecated go license yaml. 

**Environment tested:**

* Python Version (use `python --version`):
* Tekton Version (use `tkn version`):
* Kubernetes Version (use `kubectl version`):
* OS (e.g. from `/etc/os-release`):

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by yhwang** [comment]
the readme changes look good to me but those copyright year changes seems not okay to me. basically, the copyright year should be a range legally. for the new files, you always start with the current year. If you are updating an existing file and want to update the year, you could add the range to it. That's what I understand. Do you want to separate the README changes and license header changes into 2 RPs?

**Comment by Tomcli** [comment]
> the readme changes look good to me but those copyright year changes seems not okay to me. basically, the copyright year should be a range legally. for the new files, you always start with the current year. If you are updating an existing file and want to update the year, you could add the range to it. That's what I understand. Do you want to separate the README changes and license header changes into 2 RPs?

Thanks that make sense. I updated the license headers to a range now.

**Review by yhwang — APPROVED** [review]
/lgtm

**Pull request merged**
