### PR TITLE
feat(sdk): update new image config via env variables

### LINKED ISSUE #1335: TektonPipelineConf::set_bash_image_name is not working
Using 1.5.7 I have the following
```python
        default_image = 'registry.redhat.io/ubi8/python-39@sha256:3523b184212e1f2243e76d8094ab52b01ea3015471471290d011625e1763af61'
        pipeline_conf = TektonPipelineConf()
        pipeline_conf.set_condition_image_name(default_image)
        pipeline_conf.set_bash_image_name(default_image)
```
```python
        result = client.create_run_from_pipeline_func(
            pipeline_func=pipeline, arguments={
                'mlpipeline_minio_artifact_secret': mlpipeline_minio_artifact_secret
            }, pipeline_conf=pipeline_conf
        )
```

image

image

image

### PR DESCRIPTION
**Pull request by Tomcli**
**Which issue is resolved by this Pull Request:** 
Resolves #1335 

**Description of your changes:**

**Environment tested:**

* Python Version (use `python --version`):
* Tekton Version (use `tkn version`):
* Kubernetes Version (use `kubectl version`):
* OS (e.g. from `/etc/os-release`):

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by Tomcli** [comment]
cc @diegolovison, changing the base_step code for all the input and output artifact step probably requires to refactor the code into python class. Can this solution work for you?

In V2 we no longer use step injection as we will migrate all the artifacts/results logic to pull from mlmd directly.

**Comment by diegolovison** [comment]
Ok

**Comment by diegolovison** [comment]
Could we do the same for `condition_image_name`?
In this case, we will have a pattern

**Comment by Tomcli** [comment]
> Could we do the same for `condition_image_name`? In this case, we will have a pattern

Sure. Added in the latest commit.

**Review by yhwang — APPROVED** [review]
/lgtm

**Pull request merged**
