### PR TITLE
make lint

### PR DESCRIPTION
**Pull request by ckadner**
**Description of your changes:**

- Added `lint` target to `Makefile` which runs `flake8` to verify code style compliance on Python source files
- Changed `.travis.yml` to make use of the new `make lint` target
- Updated [Developer Guide](https://github.com/ckadner/kfp-tekton/tree/make_lint/sdk/python#coding-style) with instructions to use `make lint` before creating a PR
- Fixed respective [code style](https://www.flake8rules.com/) violations in Python sources

**Code style violations corrected in this PR:**
```
1     E202 whitespace before ')'
3     E203 whitespace before ':'
1     E225 missing whitespace around operator
5     E231 missing whitespace after ','
14    E251 unexpected spaces around keyword / parameter equals
16    E252 missing whitespace around parameter equals
8     E302 expected 2 blank lines, found 1
5     E303 too many blank lines (2)
2     E402 module level import not at top of file
20    F401 imported but unused
8     W291 trailing whitespace
2     W292 no newline at end of file

* https://pycodestyle.pycqa.org/en/latest/intro.html#error-codes
```

**Flake8 parameters:**
```
flake8 sdk/python \
    --select=E9,E2,E3,E5,F63,F7,F82,F4,F841,W291,W292 \
    --per-file-ignores sdk/python/tests/compiler/testdata/*:F841 \
    --max-line-length=140 \
    --count --show-source --statistics
```

### CODE REVIEW

**Comment by Tomcli** [comment]
Thanks @ckadner, I think we didn't include all the flask8 codestyle check because the original KFP didn't follow it. Do you think this will make it harder to merge back to KFP? (I do realize some places in KFP use 2 spaces indent and some other places use 4 spaces indent)

**Comment by ckadner** [comment]
> Thanks @ckadner, I think we didn't include all the flask8 codestyle check because the original KFP didn't follow it. Do you think this will make it harder to merge back to KFP? (I do realize some places in KFP use 2 spaces indent and some other places use 4 spaces indent)

Good point. There was a time when we could compare the KFP code and our code side-by-side in order to merge our changes back into KFP at some point in the future. I actually tried doing that when upgrading from KFP 0.2.2 to 0.5.0 and found that we had so much new code and so much code changed in the overridden methods that comparing side-by-side is no longer feasible. Instead, if we do want to bring this code into KFP then the `kfp_tekton` compiler would have to live in a separate package, rather then plastering _if-then-else_ code blocks all throughout the existing `kfp.compiler` package. Side-by-side comparison of code block that we did not change much still works even after this PR with the `ignore whitespace and empty lines` option enabled in many compare tools.

I excluded the rule check for the line indent to accommodate the discrepancies with the hanging line indent of 2 versus 4.

The majority of the lint error corrections I made in this PR were in the code that we added, not in the KFP code which we brought in mostly unchanged.

**Comment by ckadner** [comment]
Thanks @Tomcli !

**Comment by Tomcli** [comment]
@ckadner I can approve it once you fix the conflicts from your other PR.

**Comment by ckadner** [comment]
> @ckadner I can approve it once you fix the conflicts from your other PR.

Thanks @Tomcli -- I rebased and resolved all conflicts.

**Pull request merged**
