### PR TITLE
Use make commands for tests and report

### PR DESCRIPTION
**Pull request by ckadner**
Since @kevinyu98 added a neat new `Makefile` we should _make_ use it in our docs and for CI/CD with Travis 😄

### CODE REVIEW

**Comment by ckadner** [comment]
Thanks @Tomcli -- I just realized `make` won't look for the `Makefile` in parent directories, so I updated the wording in the `sdk/python/tests/README.md`

**Comment by Tomcli** [comment]
I think there's a bug with prow tide because it still thinks this PR is not merge. Let me try to close this can see can we skip that bug.
/close

**Comment by Tomcli** [comment]
Problem solved. Looks like reopen reset the tide stage.

**Pull request merged**
