### PR TITLE
Add csi-s3 storage class as big data passing storage

### LINKED ISSUE #569: support small K8s volume using non cloud service based storageclass
/kind feature

**Description:**
Currently on IBM Cloud, all the storage classes are created by the IKS service which has to go over 3-5 minutes billing process when dynamically creating new K8s volume. Thus, we need to have one storageclass option for quick and small volume provision without going over the IBM Cloud billing process. 

We have few options for public cloud
1. Have a predefined NFS/block storage. Then use CSI driver to create a new storage class. All the default PVCs for pipeline will be partition from this predefined volume. (This volume is used by all Kubeflow users)
2. Create a local NFS controller. However, this method could be unstable as we did try it when running Kubeflow on Openshift two years ago.

For private cloud, usually the admin purchases a big storage for all the clusters in the private cloud instead of purchasing cloud storage on the go. Thus, it might not have the bottleneck of waiting for the public cloud billing process.

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

### PR DESCRIPTION
**Pull request by Tomcli**
**Which issue is resolved by this Pull Request:** 
Resolves #569

**Description of your changes:**
- Add CSI-S3 storage class third party plugins. (Translated from Datashim's CSI S3 helm chart to kustomize)
- Add storage class configuration to big data passing (default to s3 storage), this way it doesn't need to provision new cloud storage for every new PVC.
- Use in conjunction with #751 to store the artifact in a centralized S3 artifact storage such as minio and COS. 

**Environment tested:**

* Python Version (use `python --version`):
* Tekton Version (use `tkn version`):
* Kubernetes Version (use `kubectl version`):
* OS (e.g. from `/etc/os-release`):

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by Tomcli** [comment]
@Udiknedormin This is the open source S3 CSI storage we use for mounting S3 storage. If there are other storages you want to use for mounting S3, please let us know. Thanks.

**Comment by Tomcli** [comment]
> kubectl apply -k "env/platform-agnostic/"

Sorry with the late reply. `kubectl apply -k "env/platform-agnostic/" ` should work if you are using a kubectl client that is v1.20+. I updated that as part of the developer readme.

**Review by ScrapCodes — APPROVED** [review]
Overall looks good to me !

Here we changed the default storage class to `kfp-csi-s3`, ~but the manifests installs a storage class `csi-s3`. Do you think we can add this point to documentation ?
Or can we change the manifests to install a storage class `kfp-csi-s3` by default. ~

Looks like a I missed a change, LGTM!!

**Comment by ScrapCodes** [comment]
/lgtm

Feel free to unhold, if you think this is good to go.

**Comment by ScrapCodes** [comment]
@Tomcli 
Is it normal to see a very high capacity for the PVC

```
k get pvc
NAME             STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
pvc-0fc0312d1f   Bound    pvc-9b269ff0-9efb-41eb-a714-812be702d950   9314Gi     RWO            kfp-csi-s3     18s

```
Even though the configured capacity is:
```
env | grep -i default
DEFAULT_ACCESSMODES=ReadWriteOnce
DEFAULT_STORAGE_CLASS=kfp-csi-s3
DEFAULT_STORAGE_SIZE=2Gi
```

**Comment by Tomcli** [comment]
> @Tomcli Is it normal to see a very high capacity for the PVC
> 
> ```
> k get pvc
> NAME             STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
> pvc-0fc0312d1f   Bound    pvc-9b269ff0-9efb-41eb-a714-812be702d950   9314Gi     RWO            kfp-csi-s3     18s
> ```
> 
> Even though the configured capacity is:
> 
> ```
> env | grep -i default
> DEFAULT_ACCESSMODES=ReadWriteOnce
> DEFAULT_STORAGE_CLASS=kfp-csi-s3
> DEFAULT_STORAGE_SIZE=2Gi
> ```

I think that's the default behavior of the S3 CSI because the S3 storage can be expanded without updating the PVC. (E.g. when using IBM Cloud object storage). So they used the maximum capacity for pvc as default.

**Pull request merged**
