### PR TITLE
feat(ui) Update UI to account for the When expression

### LINKED ISSUE #327: Update UI to support Tekton whenexpression spec for conditional task
/kind feature

**Description:**
We migrated the implementation for condition to use Tekton WhenExpression. There's some changes to the Tekton spec and the new implementation is more align with Argo where each condition is also treated as a "node". 

Source code is ready in this PR: https://github.com/kubeflow/kfp-tekton/pull/321

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

### PR DESCRIPTION
**Pull request by drewbutlerbb4**
**Which issue is resolved by this Pull Request:** 
Resolves #327

**Description of your changes:**
Adds an edge between dependencies based on the `when` expression.

**Environment tested:**

* Python Version (use `python --version`):
* Tekton Version (use `tkn version`):
* Kubernetes Version (use `kubectl version`):
* OS (e.g. from `/etc/os-release`):

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention). 

   PR titles examples:
    * `fix(frontend): fixes empty page. Fixes #1234`
       Use `fix` to indicate that this PR fixes a bug.
    * `feat(backend): configurable service account. Fixes #1234, fixes #1235`
       Use `feat` to indicate that this PR adds a new feature. 
    * `chore: set up changelog generation tools`
       Use `chore` to indicate that this PR makes some changes that users don't need to know.
    * `test: fix CI failure. Part of #1234`
        Use `part of` to indicate that a PR is working on an issue, but shouldn't close the issue when merged.

- [ ] Do you want this pull request (PR) cherry-picked into the current release branch?
    
    If yes, use one of the following options:
  
    * **(Recommended.)** Ask the PR approver to add the `cherrypick-approved` label to this PR. The release manager adds this PR to the release branch in a batch update.
    *  After this PR is merged, create a cherry-pick PR to add these changes to the release branch. (For more information about creating a cherry-pick PR, see the [Kubeflow Pipelines release guide](https://github.com/kubeflow/pipelines/blob/master/RELEASE.md#option--git-cherry-pick).)

### CODE REVIEW

**Comment by Tomcli** [comment]
Thanks @drewbutlerbb4, for our new "condition" task, if the results.status is false, can you mark the icon as "skipped" instead of "completed"? Thanks.

**Comment by drewbutlerbb4** [comment]
Thanks @Tomcli, I added that now

**Pull request merged**
