### PR TITLE
Fix long param compile errors

### LINKED ISSUE #548: Long task and output names
/kind bug

**What steps did you take and what happened:**
Use a long component name and a long output name.

```python
from kfp import dsl
from kfp.components import load_component_from_text
from kfp_tekton.compiler import TektonCompiler as Compiler

import uuid
import traceback


def component_str(component_id: str, output_name: str) -> str:
  return f"""
    name: {component_id}
    inputs:
    - name: input_path
      type: String
    outputs:
    - name: {output_name}
      type: String
    implementation:
      container:
        image: sth
        command:
        - else
        args:
        - inputValue: input_path
        - outputPath: {output_name}
  """


def example_gen(component_id: str, output_name: str):
  @dsl.pipeline("example")
  def example(input_path: str):
    component = load_component_from_text(
      component_str(component_id, output_name)
    )
  
    op0 = component(input_path)
    op1 = component(op0.output) # commenting this line makes it compile
  return example


if __name__ == '__main__':
  component_id_long  = str(uuid.uuid1())
  component_id_short = component_id_long[:13]

  output_name_long  = "output_with_long_name"
  output_name_short = "out_short"

  for component_id in [component_id_short, component_id_long]:
    for output_name in [output_name_short, output_name_long]:
      try:
        example = example_gen(component_id, output_name)
        Compiler().compile(example, __file__ + '.yaml')
        print(component_id, output_name)
      except RuntimeError as e:
        print(component_id, output_name)
        print(e)
        traceback.print_exc()
      print()
      print()
```

Output:
```
➜ python38 non_compliant.py
c14588d2-a13c out_short


c14588d2-a13c output_with_long_name


c14588d2-a13c-11eb-8574-acde48001122 out_short


c14588d2-a13c-11eb-8574-acde48001122 output_with_long_name
Internal compiler error: Found non-compliant Kubernetes names:
{
  "spec.pipelineSpec.tasks[1].params[0].name": "c14588d2-a13c-11eb-8574-acde48001122-output_with_long_name",
  "spec.pipelineSpec.tasks[1].taskSpec.params[0].name": "c14588d2-a13c-11eb-8574-acde48001122-output_with_long_name"
}
Please create a new issue at https://github.com/kubeflow/kfp-tekton/issues
attaching the pipeline DSL code and the pipeline YAML.
Traceback (most recent call last):
  File "non_compliant.py", line 52, in <module>
    Compiler().compile(example, __file__ + '.yaml')
  File "(...)/kfp_tekton/sdk/python/kfp_tekton/compiler/compiler.py", line 1014, in compile
    super().compile(pipeline_func, package_path, type_check, pipeline_conf=pipeline_conf)
  File "(...)/kfp/compiler/compiler.py", line 1022, in compile
    self._create_and_write_workflow(
  File "(...)/kfp_tekton/sdk/python/kfp_tekton/compiler/compiler.py", line 1121, in _create_and_write_workflow
    _validate_workflow(workflow)
  File "(...)/kfp_tekton/sdk/python/kfp_tekton/compiler/compiler.py", line 1163, in _validate_workflow
    raise RuntimeError(error_msg_tmplt % ("names", json.dumps(non_k8s_names, sort_keys=False, indent=2)))
RuntimeError: Internal compiler error: Found non-compliant Kubernetes names:
{
  "spec.pipelineSpec.tasks[1].params[0].name": "c14588d2-a13c-11eb-8574-acde48001122-output_with_long_name",
  "spec.pipelineSpec.tasks[1].taskSpec.params[0].name": "c14588d2-a13c-11eb-8574-acde48001122-output_with_long_name"
}
Please create a new issue at https://github.com/kubeflow/kfp-tekton/issues
attaching the pipeline DSL code and the pipeline YAML.
```

**What did you expect to happen:**
If the name would fail at runtime, it should be trimmed (probably trimming the task name, treating output name as suffix?), but definitely not break the compilation.

**Additional information:**
The code that throws this exception is internal kfp-tekton validation --- check if all names are sanitised.

Do result names need to follow such string sanitisation rules, just like resource names? If so, their sanitisation earlier on should be modified to pass the check.

**Environment:**

* Python Version (use `python --version`): python 3.8
* SDK Version: master's commit 0f1147e55e1a68b84d299ef90d0053ce71e84484
* Tekton Version (use `tkn version`): irrelevant
* Kubernetes Version (use `kubectl version`): irrelevant
* OS (e.g. from `/etc/os-release`): irrelevant

### PR DESCRIPTION
**Pull request by Tomcli**
**Which issue is resolved by this Pull Request:** 
Resolves #548

**Description of your changes:**
This PR introduced few changes:
1. Parameters at the param section are now capped at 128 characters (according to the kfp api requirements for displaying node id) https://github.com/kubeflow/pipelines/blob/master/frontend/src/apis/run/api.ts#L424-L429
2. The whole string size for Tekton parameters are capped at 253 because they have the same requirements as the annotation/label keys
3. The maximum op name for each opsgroup is 57 characters. Because in Tekton, opsgroup name is the same as Tekton task name which has to follow the K8S DNS label standard (with < 63 characters for the taskrun name) https://github.com/tektoncd/pipeline/blob/main/pkg/apis/pipeline/v1beta1/pipeline_types.go#L256-L262
4. In addition to No.3, op name is no longer sanitize the length. We will throw an error for any op name that's greater than 57 characters. This is because when multiple ops have the same name, the DSL only append `-2` to the op name to make each op have a unique name. However, the sanitize function may trimmed the unique identifier that sanitize the length which causes conflicts. Furthermore, the trimmed op name also needs to be reflected in the task param name, which can get very complicated towards the end of the compilation. In KFP Argo, it also throw an error when the op name is over the Argo limit (128 characters).

**Environment tested:**

* Python Version (use `python --version`):
* Tekton Version (use `tkn version`):
* Kubernetes Version (use `kubectl version`):
* OS (e.g. from `/etc/os-release`):

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention). 

- [ ] Do you want this pull request (PR) cherry-picked into the current release branch?

    [Learn more about cherry-picking updates into the release branch](https://github.com/kubeflow/pipelines/blob/master/RELEASE.md#cherry-picking-pull-requests-to-release-branch).

### CODE REVIEW

**Comment by Tomcli** [comment]
@Udiknedormin

**Comment by Udiknedormin** [comment]
@Tomcli Based on my sample test case, it looks like it does solve the problem.

We will have the new name length requirements in mind.

**Comment by Tomcli** [comment]
@drewbutlerbb4 @ckadner Can one of you review this and lgtm? Thanks

**Pull request merged**
