### PR TITLE
Fix the yaml dump issue of boolean value

### LINKED ISSUE #664: Single character parameters need to have double quote to avoid yaml keyword conflicts
I think this is a bug, we should have double quote on single character parameter for n and y to avoid this issue. For now I will lgtm and open another issue for it

_Originally posted by @Tomcli in https://github.com/kubeflow/kfp-tekton/pull/660#discussion_r666403707_

### PR DESCRIPTION
**Pull request by pugangxa**
**Which issue is resolved by this Pull Request:** 
Resolves #664 

**Description of your changes:**
In test to dump yaml should use the same method as is in compile which is customized to process the boolean values.

### CODE REVIEW

**Comment by Tomcli** [comment]
cc @Udiknedormin

**Comment by Tomcli** [comment]
@pugangxa can you also update this file with parameter name `n`? thanks
https://github.com/kubeflow/kfp-tekton/blob/master/sdk/python/tests/compiler/testdata/conditions_with_global_params.py

**Comment by pugangxa** [comment]
> @pugangxa can you also update this file with parameter name `n`? thanks
> https://github.com/kubeflow/kfp-tekton/blob/master/sdk/python/tests/compiler/testdata/conditions_with_global_params.py

Sure, updated.

**Pull request merged**
