### PR TITLE
Enable cache server for tekton

### PR DESCRIPTION
**Pull request by vincent-pli**
**Which issue is resolved by this Pull Request:** 
Resolves #

**Description of your changes:**
The PR enabled the cache server in `Tekton` scenario, basically it's not change the behavior of `Argo` version, just make it works with `Tekton`.

The PR is only for backend(golang), for DSL part and GUI part still on going, maybe submit later. 
@animeshsingh @Tomcli @fenglixa 

**Environment tested:**

* Python Version (use `python --version`):
* Tekton Version (use `tkn version`):
* Kubernetes Version (use `kubectl version`):
* OS (e.g. from `/etc/os-release`):

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention). 

   PR titles examples:
    * `fix(frontend): fixes empty page. Fixes #1234`
       Use `fix` to indicate that this PR fixes a bug.
    * `feat(backend): configurable service account. Fixes #1234, fixes #1235`
       Use `feat` to indicate that this PR adds a new feature. 
    * `chore: set up changelog generation tools`
       Use `chore` to indicate that this PR makes some changes that users don't need to know.
    * `test: fix CI failure. Part of #1234`
        Use `part of` to indicate that a PR is working on an issue, but shouldn't close the issue when merged.

- [ ] Do you want this pull request (PR) cherry-picked into the current release branch?
    
    If yes, use one of the following options:
  
    * **(Recommended.)** Ask the PR approver to add the `cherrypick-approved` label to this PR. The release manager adds this PR to the release branch in a batch update.
    *  After this PR is merged, create a cherry-pick PR to add these changes to the release branch. (For more information about creating a cherry-pick PR, see the [Kubeflow Pipelines release guide](https://github.com/kubeflow/pipelines/blob/master/RELEASE.md#option--git-cherry-pick).)

### CODE REVIEW

**Comment by Tomcli** [comment]
thanks @vincent-pli, since your PR also update the argo client. can you wait for #423 to merge so we can make the go.mod dependencies consistent?

**Comment by vincent-pli** [comment]
@Tomcli 
Sure, will `rebase` after that PR merged.

**Comment by Tomcli** [comment]
@vincent-pli can you rebase this PR? thanks.

**Comment by Tomcli** [comment]
@vincent-pli are you able to rebase this PR? thanks

**Comment by vincent-pli** [comment]
@Tomcli 
Sorry for delay, I will rebase it very soon, thanks

**Comment by Tomcli** [comment]
Here is the build errors I got
```
# github.com/kubeflow/pipelines/backend/src/cache/client
backend/src/cache/client/kubernetes_core_fake.go:30:10: cannot use c.podClientFake (type *FakePodClient) as type "k8s.io/client-go/kubernetes/typed/core/v1".PodInterface in return argument:
	*FakePodClient does not implement "k8s.io/client-go/kubernetes/typed/core/v1".PodInterface (wrong type for Bind method)
		have Bind(*"k8s.io/api/core/v1".Binding) error
		want Bind(context.Context, *"k8s.io/api/core/v1".Binding, "k8s.io/apimachinery/pkg/apis/meta/v1".CreateOptions) error
backend/src/cache/client/kubernetes_core_fake.go:46:10: cannot use c.podClientFake (type *FakeBadPodClient) as type "k8s.io/client-go/kubernetes/typed/core/v1".PodInterface in return argument:
	*FakeBadPodClient does not implement "k8s.io/client-go/kubernetes/typed/core/v1".PodInterface (wrong type for Bind method)
		have Bind(*"k8s.io/api/core/v1".Binding) error
		want Bind(context.Context, *"k8s.io/api/core/v1".Binding, "k8s.io/apimachinery/pkg/apis/meta/v1".CreateOptions) error
backend/src/cache/client/tekton.go:27:70: not enough arguments in call to c.tektonV1beta1Client.TektonV1beta1().TaskRuns(namespace).Get
	have (string, "k8s.io/apimachinery/pkg/apis/meta/v1".GetOptions)
	want (context.Context, string, "k8s.io/apimachinery/pkg/apis/meta/v1".GetOptions)
(base) tommys-mbp:pipelines tommyli$ go build -o cache ./backend/src/cache
# github.com/kubeflow/pipelines/backend/src/cache/client
backend/src/cache/client/kubernetes_core_fake.go:30:10: cannot use c.podClientFake (type *FakePodClient) as type "k8s.io/client-go/kubernetes/typed/core/v1".PodInterface in return argument:
	*FakePodClient does not implement "k8s.io/client-go/kubernetes/typed/core/v1".PodInterface (wrong type for Bind method)
		have Bind(*"k8s.io/api/core/v1".Binding) error
		want Bind(context.Context, *"k8s.io/api/core/v1".Binding, "k8s.io/apimachinery/pkg/apis/meta/v1".CreateOptions) error
backend/src/cache/client/kubernetes_core_fake.go:46:10: cannot use c.podClientFake (type *FakeBadPodClient) as type "k8s.io/client-go/kubernetes/typed/core/v1".PodInterface in return argument:
	*FakeBadPodClient does not implement "k8s.io/client-go/kubernetes/typed/core/v1".PodInterface (wrong type for Bind method)
		have Bind(*"k8s.io/api/core/v1".Binding) error
		want Bind(context.Context, *"k8s.io/api/core/v1".Binding, "k8s.io/apimachinery/pkg/apis/meta/v1".CreateOptions) error
backend/src/cache/client/tekton.go:27:70: not enough arguments in call to c.tektonV1beta1Client.TektonV1beta1().TaskRuns(namespace).Get
	have (string, "k8s.io/apimachinery/pkg/apis/meta/v1".GetOptions)
	want (context.Context, string, "k8s.io/apimachinery/pkg/apis/meta/v1".GetOptions)
```

**Comment by Tomcli** [comment]
As part of moving the Tekton go client to 0.19+, we also needed to move the Kubernetes client-go package to 0.18+ which introduced the new function syntax.

**Comment by Tomcli** [comment]
Here is the example from tekton https://github.com/tektoncd/pipeline/pull/3319/files#diff-3b3ca39720cb7f55cf1c1529cee802b2f712fcbec78de47484eb3fc5f1d0eed5R34

For kfp-tekton, most of the time I just passed context.Background()
https://github.com/kubeflow/kfp-tekton/commit/142c9d1256b48d7665e9cdc4ec28b5bf06c52b70

**Comment by vincent-pli** [comment]
@Tomcli 
Thanks, the issue has been fix, please try again.

**Comment by Tomcli** [comment]
/lgtm
/approve
/hold

thanks @vincent-pli, what do we need to change in the pipelinerun in order to enable this cache feature? we want to create an example to test this feature.

**Comment by Tomcli** [comment]
@vincent-pli I can merge this now since it has no actual impact to our current pipelines. Can you add an example when you introduce this in the compiler/sdk? thanks.
/unhold

**Pull request merged**
