### PR TITLE
add manifest for 0.8.0-rc0

### PR DESCRIPTION
**Pull request by Tomcli**
**Which issue is resolved by this Pull Request:** 
Resolves #

**Description of your changes:**
Sync with https://github.com/kubeflow/manifests/pull/1824.

This should be the last PR before cutting the 0.8.0-rc0 github tag. Please note that we are not creating releases for RCs so there will be no release note.

0.8.0-rc0 will include Tekton 0.21.0 deployment as part of the manifest install to follow the new KFP standard.

**Environment tested:**

* Python Version (use `python --version`):
* Tekton Version (use `tkn version`):
* Kubernetes Version (use `kubectl version`):
* OS (e.g. from `/etc/os-release`):

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention). 

- [ ] Do you want this pull request (PR) cherry-picked into the current release branch?

    [Learn more about cherry-picking updates into the release branch](https://github.com/kubeflow/pipelines/blob/master/RELEASE.md#cherry-picking-pull-requests-to-release-branch).

### CODE REVIEW

**Review by ckadner — APPROVED** [review]

**Comment by Tomcli** [comment]
@ckadner can you lgtm this PR? kfp 1.5.0-rc3 will have changes to the manifest, so we want to stage this change in our rc0 before further rebasing. 

This manifest is tested with the kubeflow/manifests already.

**Comment by Tomcli** [comment]
/hold

looks like the new knative stack with tekton has conflicts due to this issue. Need to update our tekton deployment a little bit. https://github.com/tektoncd/pipeline/issues/1803

**Comment by ckadner** [comment]
Thanks @Tommy

/lgtm

**Pull request merged**
