### PR TITLE
Add KFP-TFX on-prem example

### PR DESCRIPTION
**Pull request by Tomcli**
- Move the current tekton example under `samples/kfp-tekton`
- Add new TFX taxi on prem example.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kfp-tekton/5)

### CODE REVIEW

**Comment by wyljpn** [comment]
Hi, recently I am working on tfx and kubeflow.
I wanted to serve the model with KFServing as this example.
https://github.com/kubeflow/kfp-tekton/tree/master/samples/kfp-tfx/tfx-taxi-on-prem

By running TFX-taxi-sample-pvc.py, we can get a YAML file containing tfx components; running kfs.py, we can get a YAML file containing only tfserving component.
How we can get the YAML file, tfx-kfs.yaml, containing both tfx components and tfserving component?

**Comment by Tomcli** [comment]
@wyljpn At the time of writing this example, I have to compile two yaml from `TFX-taxi-sample-pvc.py` and `kfs.py` and merge them manually because TFX SDK doesn't support genetic Kubeflow components. KFP does have plan to make TFX and KFP closer in the V2 API, but it will be coming in October which we don't have access right now.

**Comment by wyljpn** [comment]
Hi @Tomcli , thank you for your quick response. 
Can't wait to use V2 API.  :)

**Comment by wyljpn** [comment]
May I ask a question?
I wrote code similar to `kfs.py` .  

```python

import kfp.compiler as compiler
import kfp.dsl as dsl
from kfp import components

kfserving_op = components.load_component_from_url('https://raw.githubusercontent.com/kubeflow/pipelines/'
                                                  'master/components/kubeflow/kfserving/component.yaml')

tfserving_yaml = '''
apiVersion: "serving.kubeflow.org/v1beta1"
kind: "InferenceService"
metadata:
    name: "rflowdemo"
    namespace: rflow
spec:
    predictor:
        tensorflow:
            storageUri: "pvc://tfx-pvc/output/Pusher/pushed_model"
            runtimeVersion: 2.4.0
'''

@dsl.pipeline(
    name='KFServing pipeline',
    description='A pipeline for KFServing.'
)
def kfservingPipeline():
    task1 = kfserving_op(
        action='apply',
        inferenceservice_yaml=tfserving_yaml
    )
    # Disable caching 
    task1.execution_options.caching_strategy.max_cache_staleness = "P0D"
  

if __name__ == '__main__':
    compiler.Compiler().compile(kfservingPipeline, __file__ + '-yaml-label.tar.gz')
```

Running the code I got a YAML file.
After uploaded and ran the pipeline, a predictor deploy and pod were created.

Log of Kubeflow - Serve Model using KFServing
```
NAME                 READY                           PREV                    LATEST URL                                                              
rflowdemo            Unknown                            0                       100                                                                  
rflowdemo            Unknown                            0                       100                                                                  
rflowdemo            Unknown                            0                       100                                                                  
rflowdemo            Unknown                            0                       100                                                                  
rflowdemo            True                               0                       100 
http://rflowdemo.rflow.example.com
                               
{'apiVersion': 'serving.kubeflow.org/v1beta1', 'kind': 'InferenceService', 'metadata': {'creationTimestamp': '2021-07-01T04:52:17Z', 'finalizers': ['inferenceservice.finalizers'], 'generation': 1, 'labels': {'pipelines.kubeflow.org/cache_enabled': 'false'}, 'managedFields': [{'apiVersion': 'serving.kubeflow.org/v1beta1', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:metadata': {'f:labels': {'.': {}, 'f:pipelines.kubeflow.org/cache_enabled': {}}}, 'f:spec': {'.': {}, 'f:predictor': {'.': {}, 'f:tensorflow': {'.': {}, 'f:runtimeVersion': {}, 'f:storageUri': {}}}}}, 'manager': 'OpenAPI-Generator', 'operation': 'Update', 'time': '2021-07-01T04:52:14Z'}, {'apiVersion': 'serving.kubeflow.org/v1beta1', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:metadata': {'f:finalizers': {}}, 'f:spec': {'f:predictor': {'f:containers': {}, 'f:tensorflow': {'f:args': {}, 'f:command': {}, 'f:image': {}}}}, 'f:status': {'.': {}, 'f:address': {'.': {}, 'f:url': {}}, 'f:components': {'.': {}, 'f:predictor': {'.': {}, 'f:address': {'.': {}, 'f:url': {}}, 'f:latestCreatedRevision': {}, 'f:latestReadyRevision': {}, 'f:latestRolledoutRevision': {}, 'f:traffic': {}, 'f:url': {}}}, 'f:conditions': {}, 'f:url': {}}}, 'manager': 'manager', 'operation': 'Update', 'time': '2021-07-01T04:52:59Z'}], 'name': 'rflowdemo', 'namespace': 'rflow', 'resourceVersion': '310528', 'uid': 'e57c37a1-db56-44e9-98d0-abce8f167dbf'}, 'spec': {'predictor': {'tensorflow': {'name': 'kfserving-container', 'resources': {'limits': {'cpu': '1', 'memory': '2Gi'}, 'requests': {'cpu': '1', 'memory': '2Gi'}}, 'runtimeVersion': '2.4.0', 'storageUri': 'pvc://tfx-pvc/output/Pusher/pushed_model'}}}, 'status': {'address': {'url': '
http://rflowdemo.rflow.svc.cluster.local/v1/models/rflowdemo:predict
'}, 'components': {'predictor': {'address': {'url': 'http://rflowdemo-predictor-default.rflow.svc.cluster.local'}, 'latestCreatedRevision': 'rflowdemo-predictor-default-rsgpg', 'latestReadyRevision': 'rflowdemo-predictor-default-rsgpg', 'latestRolledoutRevision': 'rflowdemo-predictor-default-rsgpg', 'traffic': [{'latestRevision': True, 'percent': 100, 'revisionName': 'rflowdemo-predictor-default-rsgpg'}], 'url': 'http://rflowdemo-predictor-default.rflow.example.com'}}, 'conditions': [{'lastTransitionTime': '2021-07-01T04:52:59Z', 'status': 'True', 'type': 'IngressReady'}, {'lastTransitionTime': '2021-07-01T04:52:59Z', 'severity': 'Info', 'status': 'True', 'type': 'PredictorConfigurationReady'}, {'lastTransitionTime': '2021-07-01T04:52:59Z', 'status': 'True', 'type': 'PredictorReady'}, {'lastTransitionTime': '2021-07-01T04:52:58Z', 'severity': 'Info', 'status': 'True', 'type': 'PredictorRouteReady'}, {'lastTransitionTime': '2021-07-01T04:52:59Z', 'status': 'True', 'type': 'Ready'}], 'url': 'http://rflowdemo.rflow.example.com'}}
http://rflowdemo-predictor-default.rflow.svc.cluster.local
'}, 'latestCreatedRevision': 'rflowdemo-predictor-default-rsgpg', 'latestReadyRevision': 'rflowdemo-predictor-default-rsgpg', 'latestRolledoutRevision': 'rflowdemo-predictor-default-rsgpg', 'traffic': [{'latestRevision': True, 'percent': 100, 'revisionName': 'rflowdemo-predictor-default-rsgpg'}], 'url': 'http://rflowdemo-predictor-default.rflow.example.com'}}, 'conditions': [{'lastTransitionTime': '2021-07-01T04:52:59Z', 'status': 'True', 'type': 'IngressReady'}, {'lastTransitionTime': '2021-07-01T04:52:59Z', 'severity': 'Info', 'status': 'True', 'type': 'PredictorConfigurationReady'}, {'lastTransitionTime': '2021-07-01T04:52:59Z', 'status': 'True', 'type': 'PredictorReady'}, {'lastTransitionTime': '2021-07-01T04:52:58Z', 'severity': 'Info', 'status': 'True', 'type': 'PredictorRouteReady'}, {'lastTransitionTime': '2021-07-01T04:52:59Z', 'status': 'True', 'type': 'Ready'}], 'url': 'http://rflowdemo.rflow.example.com'}}
http://rflowdemo-predictor-default.rflow.example.com
'}}, 'conditions': [{'lastTransitionTime': '2021-07-01T04:52:59Z', 'status': 'True', 'type': 'IngressReady'}, {'lastTransitionTime': '2021-07-01T04:52:59Z', 'severity': 'Info', 'status': 'True', 'type': 'PredictorConfigurationReady'}, {'lastTransitionTime': '2021-07-01T04:52:59Z', 'status': 'True', 'type': 'PredictorReady'}, {'lastTransitionTime': '2021-07-01T04:52:58Z', 'severity': 'Info', 'status': 'True', 'type': 'PredictorRouteReady'}, {'lastTransitionTime': '2021-07-01T04:52:59Z', 'status': 'True', 'type': 'Ready'}], 'url': 'http://rflowdemo.rflow.example.com'}}
http://rflowdemo.rflow.example.com
'}}
Model is ready
http://rflowdemo.rflow.example.com
 is the Knative domain.
Sample test commands: 
curl -v -X GET 
http://rflowdemo.rflow.example.com
If the above URL is not accessible, it's recommended to setup Knative with a configured DNS.
https://knative.dev/docs/install/installing-istio/#configuring-dns
```

Log of the predictor pod (KFServing will load the model with MAX version number, 59 in this case)
```
$kubectl logs rflowdemo-predictor-default-6ckff-deployment-79b5bb64cc-4c85l -n rflow storage-initializer
[I 210701 04:54:14 initializer-entrypoint:13] Initializing, args: src_uri [/mnt/pvc/output/Pusher/pushed_model] dest_path[ [/mnt/models]
[I 210701 04:54:14 storage:45] Copying contents of /mnt/pvc/output/Pusher/pushed_model to local
[I 210701 04:54:14 storage:223] Linking: /mnt/pvc/output/Pusher/pushed_model/59 to /mnt/models/59
```


So far so good.
But if a new version of a model is pushed, we run the pipeline again.
it will not delete the old pod and create a new one or update the pod for the new version of the model,
it seems that the component just finished without doing anything.

Log of Kubeflow - Serve Model using KFServing
```
NAME                 READY                           PREV                    LATEST URL                                                              
rflowdemo            True                               0                       100 
http://rflowdemo.rflow.example.com
                               
{'apiVersion': 'serving.kubeflow.org/v1beta1', 'kind': 'InferenceService', 'metadata': {'creationTimestamp': '2021-07-01T04:54:07Z', 'finalizers': ['inferenceservice.finalizers'], 'generation': 1, 'labels': {'pipelines.kubeflow.org/cache_enabled': 'false'}, 'managedFields': [{'apiVersion': 'serving.kubeflow.org/v1beta1', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:metadata': {'f:labels': {'.': {}, 'f:pipelines.kubeflow.org/cache_enabled': {}}}, 'f:spec': {'.': {}, 'f:predictor': {'.': {}, 'f:tensorflow': {'.': {}, 'f:runtimeVersion': {}, 'f:storageUri': {}}}}}, 'manager': 'OpenAPI-Generator', 'operation': 'Update', 'time': '2021-07-01T04:54:05Z'}, {'apiVersion': 'serving.kubeflow.org/v1beta1', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:metadata': {'f:finalizers': {}}, 'f:spec': {'f:predictor': {'f:containers': {}, 'f:tensorflow': {'f:args': {}, 'f:command': {}, 'f:image': {}}}}, 'f:status': {'.': {}, 'f:address': {'.': {}, 'f:url': {}}, 'f:components': {'.': {}, 'f:predictor': {'.': {}, 'f:address': {'.': {}, 'f:url': {}}, 'f:latestCreatedRevision': {}, 'f:latestReadyRevision': {}, 'f:latestRolledoutRevision': {}, 'f:traffic': {}, 'f:url': {}}}, 'f:conditions': {}, 'f:url': {}}}, 'manager': 'manager', 'operation': 'Update', 'time': '2021-07-01T04:54:28Z'}], 'name': 'rflowdemo', 'namespace': 'rflow', 'resourceVersion': '311008', 'uid': '5aca4827-dceb-4263-bd48-9146960fee4c'}, 'spec': {'predictor': {'tensorflow': {'name': 'kfserving-container', 'resources': {'limits': {'cpu': '1', 'memory': '2Gi'}, 'requests': {'cpu': '1', 'memory': '2Gi'}}, 'runtimeVersion': '2.4.0', 'storageUri': 'pvc://tfx-pvc/output/Pusher/pushed_model'}}}, 'status': {'address': {'url': '
http://rflowdemo.rflow.svc.cluster.local/v1/models/rflowdemo:predict
'}, 'components': {'predictor': {'address': {'url': 'http://rflowdemo-predictor-default.rflow.svc.cluster.local'}, 'latestCreatedRevision': 'rflowdemo-predictor-default-6ckff', 'latestReadyRevision': 'rflowdemo-predictor-default-6ckff', 'latestRolledoutRevision': 'rflowdemo-predictor-default-6ckff', 'traffic': [{'latestRevision': True, 'percent': 100, 'revisionName': 'rflowdemo-predictor-default-6ckff'}], 'url': 'http://rflowdemo-predictor-default.rflow.example.com'}}, 'conditions': [{'lastTransitionTime': '2021-07-01T04:54:28Z', 'status': 'True', 'type': 'IngressReady'}, {'lastTransitionTime': '2021-07-01T04:54:28Z', 'severity': 'Info', 'status': 'True', 'type': 'PredictorConfigurationReady'}, {'lastTransitionTime': '2021-07-01T04:54:28Z', 'status': 'True', 'type': 'PredictorReady'}, {'lastTransitionTime': '2021-07-01T04:54:27Z', 'severity': 'Info', 'status': 'True', 'type': 'PredictorRouteReady'}, {'lastTransitionTime': '2021-07-01T04:54:28Z', 'status': 'True', 'type': 'Ready'}], 'url': 'http://rflowdemo.rflow.example.com'}}
http://rflowdemo-predictor-default.rflow.svc.cluster.local
'}, 'latestCreatedRevision': 'rflowdemo-predictor-default-6ckff', 'latestReadyRevision': 'rflowdemo-predictor-default-6ckff', 'latestRolledoutRevision': 'rflowdemo-predictor-default-6ckff', 'traffic': [{'latestRevision': True, 'percent': 100, 'revisionName': 'rflowdemo-predictor-default-6ckff'}], 'url': 'http://rflowdemo-predictor-default.rflow.example.com'}}, 'conditions': [{'lastTransitionTime': '2021-07-01T04:54:28Z', 'status': 'True', 'type': 'IngressReady'}, {'lastTransitionTime': '2021-07-01T04:54:28Z', 'severity': 'Info', 'status': 'True', 'type': 'PredictorConfigurationReady'}, {'lastTransitionTime': '2021-07-01T04:54:28Z', 'status': 'True', 'type': 'PredictorReady'}, {'lastTransitionTime': '2021-07-01T04:54:27Z', 'severity': 'Info', 'status': 'True', 'type': 'PredictorRouteReady'}, {'lastTransitionTime': '2021-07-01T04:54:28Z', 'status': 'True', 'type': 'Ready'}], 'url': 'http://rflowdemo.rflow.example.com'}}
http://rflowdemo-predictor-default.rflow.example.com
'}}, 'conditions': [{'lastTransitionTime': '2021-07-01T04:54:28Z', 'status': 'True', 'type': 'IngressReady'}, {'lastTransitionTime': '2021-07-01T04:54:28Z', 'severity': 'Info', 'status': 'True', 'type': 'PredictorConfigurationReady'}, {'lastTransitionTime': '2021-07-01T04:54:28Z', 'status': 'True', 'type': 'PredictorReady'}, {'lastTransitionTime': '2021-07-01T04:54:27Z', 'severity': 'Info', 'status': 'True', 'type': 'PredictorRouteReady'}, {'lastTransitionTime': '2021-07-01T04:54:28Z', 'status': 'True', 'type': 'Ready'}], 'url': 'http://rflowdemo.rflow.example.com'}}
http://rflowdemo.rflow.example.com
'}}
Model is ready
http://rflowdemo.rflow.example.com
 is the Knative domain.
Sample test commands: 
curl -v -X GET 
http://rflowdemo.rflow.example.com
If the above URL is not accessible, it's recommended to setup Knative with a configured DNS.
https://knative.dev/docs/install/installing-istio/#configuring-dns
```

We need to delete the inferenceservice running command ` $ kubectl delete inferenceservice -n rflow rflowdemo`
then run the pipeline again. 
This time it will load and serve the new version of the model.

```
$ kubectl logs rflowdemo-predictor-default-nf72v-deployment-746b56c98c-xtzfc -n rflow storage-initializer
[I 210701 05:18:31 initializer-entrypoint:13] Initializing, args: src_uri [/mnt/pvc/output/Pusher/pushed_model] dest_path[ [/mnt/models]
[I 210701 05:18:31 storage:45] Copying contents of /mnt/pvc/output/Pusher/pushed_model to local
[I 210701 05:18:31 storage:223] Linking: /mnt/pvc/output/Pusher/pushed_model/59 to /mnt/models/59
[I 210701 05:18:31 storage:223] Linking: /mnt/pvc/output/Pusher/pushed_model/69 to /mnt/models/69
```

It is not a good experience.
Does any method let KFServing component detect versions of the model, so we can run the pipeline without deleting the existing inferenceservice manually?

**Comment by wyljpn** [comment]
> @Tomcli May I ask a question about using KFServing component on Kubeflow?
> 
> I wrote a python file similar to `kfs.py` .
> 
> ```python
> import kfp.compiler as compiler
> import kfp.dsl as dsl
> from kfp import components
> 
> kfserving_op = components.load_component_from_url('https://raw.githubusercontent.com/kubeflow/pipelines/'
>                                                   'master/components/kubeflow/kfserving/component.yaml')
> 
> tfserving_yaml = '''
> apiVersion: "serving.kubeflow.org/v1beta1"
> kind: "InferenceService"
> metadata:
>     name: "rflowdemo"
>     namespace: rflow
> spec:
>     predictor:
>         tensorflow:
>             storageUri: "pvc://tfx-pvc/output/Pusher/pushed_model"
>             runtimeVersion: 2.4.0
> '''
> 
> @dsl.pipeline(
>     name='KFServing pipeline',
>     description='A pipeline for KFServing.'
> )
> def kfservingPipeline():
>     task1 = kfserving_op(
>         action='apply',
>         inferenceservice_yaml=tfserving_yaml
>     )
>     # Disable caching 
>     task1.execution_options.caching_strategy.max_cache_staleness = "P0D"
>   
> 
> if __name__ == '__main__':
>     compiler.Compiler().compile(kfservingPipeline, __file__ + '-yaml-label.tar.gz')
> ```
> 
> Running the code I got a YAML file.
> After uploaded and ran the pipeline, a predictor deploy and pod were created.
> 
> Log of Kubeflow - Serve Model using KFServing
> 
> ```
> NAME                 READY                           PREV                    LATEST URL                                                              
> rflowdemo            Unknown                            0                       100                                                                  
> rflowdemo            Unknown                            0                       100                                                                  
> rflowdemo            Unknown                            0                       100                                                                  
> rflowdemo            Unknown                            0                       100                                                                  
> rflowdemo            True                               0                       100 
> http://rflowdemo.rflow.example.com
>                                
> {'apiVersion': 'serving.kubeflow.org/v1beta1', 'kind': 'InferenceService', 'metadata': {'creationTimestamp': '2021-07-01T04:52:17Z', 'finalizers': ['inferenceservice.finalizers'], 'generation': 1, 'labels': {'pipelines.kubeflow.org/cache_enabled': 'false'}, 'managedFields': [{'apiVersion': 'serving.kubeflow.org/v1beta1', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:metadata': {'f:labels': {'.': {}, 'f:pipelines.kubeflow.org/cache_enabled': {}}}, 'f:spec': {'.': {}, 'f:predictor': {'.': {}, 'f:tensorflow': {'.': {}, 'f:runtimeVersion': {}, 'f:storageUri': {}}}}}, 'manager': 'OpenAPI-Generator', 'operation': 'Update', 'time': '2021-07-01T04:52:14Z'}, {'apiVersion': 'serving.kubeflow.org/v1beta1', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:metadata': {'f:finalizers': {}}, 'f:spec': {'f:predictor': {'f:containers': {}, 'f:tensorflow': {'f:args': {}, 'f:command': {}, 'f:image': {}}}}, 'f:status': {'.': {}, 'f:address': {'.': {}, 'f:url': {}}, 'f:components': {'.': {}, 'f:predictor': {'.': {}, 'f:address': {'.': {}, 'f:url': {}}, 'f:latestCreatedRevision': {}, 'f:latestReadyRevision': {}, 'f:latestRolledoutRevision': {}, 'f:traffic': {}, 'f:url': {}}}, 'f:conditions': {}, 'f:url': {}}}, 'manager': 'manager', 'operation': 'Update', 'time': '2021-07-01T04:52:59Z'}], 'name': 'rflowdemo', 'namespace': 'rflow', 'resourceVersion': '310528', 'uid': 'e57c37a1-db56-44e9-98d0-abce8f167dbf'}, 'spec': {'predictor': {'tensorflow': {'name': 'kfserving-container', 'resources': {'limits': {'cpu': '1', 'memory': '2Gi'}, 'requests': {'cpu': '1', 'memory': '2Gi'}}, 'runtimeVersion': '2.4.0', 'storageUri': 'pvc://tfx-pvc/output/Pusher/pushed_model'}}}, 'status': {'address': {'url': '
> http://rflowdemo.rflow.svc.cluster.local/v1/models/rflowdemo:predict
> '}, 'components': {'predictor': {'address': {'url': 'http://rflowdemo-predictor-default.rflow.svc.cluster.local'}, 'latestCreatedRevision': 'rflowdemo-predictor-default-rsgpg', 'latestReadyRevision': 'rflowdemo-predictor-default-rsgpg', 'latestRolledoutRevision': 'rflowdemo-predictor-default-rsgpg', 'traffic': [{'latestRevision': True, 'percent': 100, 'revisionName': 'rflowdemo-predictor-default-rsgpg'}], 'url': 'http://rflowdemo-predictor-default.rflow.example.com'}}, 'conditions': [{'lastTransitionTime': '2021-07-01T04:52:59Z', 'status': 'True', 'type': 'IngressReady'}, {'lastTransitionTime': '2021-07-01T04:52:59Z', 'severity': 'Info', 'status': 'True', 'type': 'PredictorConfigurationReady'}, {'lastTransitionTime': '2021-07-01T04:52:59Z', 'status': 'True', 'type': 'PredictorReady'}, {'lastTransitionTime': '2021-07-01T04:52:58Z', 'severity': 'Info', 'status': 'True', 'type': 'PredictorRouteReady'}, {'lastTransitionTime': '2021-07-01T04:52:59Z', 'status': 'True', 'type': 'Ready'}], 'url': 'http://rflowdemo.rflow.example.com'}}
> http://rflowdemo-predictor-default.rflow.svc.cluster.local
> '}, 'latestCreatedRevision': 'rflowdemo-predictor-default-rsgpg', 'latestReadyRevision': 'rflowdemo-predictor-default-rsgpg', 'latestRolledoutRevision': 'rflowdemo-predictor-default-rsgpg', 'traffic': [{'latestRevision': True, 'percent': 100, 'revisionName': 'rflowdemo-predictor-default-rsgpg'}], 'url': 'http://rflowdemo-predictor-default.rflow.example.com'}}, 'conditions': [{'lastTransitionTime': '2021-07-01T04:52:59Z', 'status': 'True', 'type': 'IngressReady'}, {'lastTransitionTime': '2021-07-01T04:52:59Z', 'severity': 'Info', 'status': 'True', 'type': 'PredictorConfigurationReady'}, {'lastTransitionTime': '2021-07-01T04:52:59Z', 'status': 'True', 'type': 'PredictorReady'}, {'lastTransitionTime': '2021-07-01T04:52:58Z', 'severity': 'Info', 'status': 'True', 'type': 'PredictorRouteReady'}, {'lastTransitionTime': '2021-07-01T04:52:59Z', 'status': 'True', 'type': 'Ready'}], 'url': 'http://rflowdemo.rflow.example.com'}}
> http://rflowdemo-predictor-default.rflow.example.com
> '}}, 'conditions': [{'lastTransitionTime': '2021-07-01T04:52:59Z', 'status': 'True', 'type': 'IngressReady'}, {'lastTransitionTime': '2021-07-01T04:52:59Z', 'severity': 'Info', 'status': 'True', 'type': 'PredictorConfigurationReady'}, {'lastTransitionTime': '2021-07-01T04:52:59Z', 'status': 'True', 'type': 'PredictorReady'}, {'lastTransitionTime': '2021-07-01T04:52:58Z', 'severity': 'Info', 'status': 'True', 'type': 'PredictorRouteReady'}, {'lastTransitionTime': '2021-07-01T04:52:59Z', 'status': 'True', 'type': 'Ready'}], 'url': 'http://rflowdemo.rflow.example.com'}}
> http://rflowdemo.rflow.example.com
> '}}
> Model is ready
> http://rflowdemo.rflow.example.com
>  is the Knative domain.
> Sample test commands: 
> curl -v -X GET 
> http://rflowdemo.rflow.example.com
> If the above URL is not accessible, it's recommended to setup Knative with a configured DNS.
> https://knative.dev/docs/install/installing-istio/#configuring-dns
> ```
> 
> Log of the predictor pod (KFServing will load the model with MAX version number, 59 in this case)
> 
> ```
> $kubectl logs rflowdemo-predictor-default-6ckff-deployment-79b5bb64cc-4c85l -n rflow storage-initializer
> [I 210701 04:54:14 initializer-entrypoint:13] Initializing, args: src_uri [/mnt/pvc/output/Pusher/pushed_model] dest_path[ [/mnt/models]
> [I 210701 04:54:14 storage:45] Copying contents of /mnt/pvc/output/Pusher/pushed_model to local
> [I 210701 04:54:14 storage:223] Linking: /mnt/pvc/output/Pusher/pushed_model/59 to /mnt/models/59
> ```
> 
> So far so good, it loads and serves the model successfully.
> 
> But if a new version of a model is pushed, we run the pipeline again.
> It will not delete the old pod and create a new one or update the pod for the new version of the model,
> it seems that the component just finished without doing anything.
> 
> Log of Kubeflow - Serve Model using KFServing
> 
> ```
> NAME                 READY                           PREV                    LATEST URL                                                              
> rflowdemo            True                               0                       100 
> http://rflowdemo.rflow.example.com
>                                
> {'apiVersion': 'serving.kubeflow.org/v1beta1', 'kind': 'InferenceService', 'metadata': {'creationTimestamp': '2021-07-01T04:54:07Z', 'finalizers': ['inferenceservice.finalizers'], 'generation': 1, 'labels': {'pipelines.kubeflow.org/cache_enabled': 'false'}, 'managedFields': [{'apiVersion': 'serving.kubeflow.org/v1beta1', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:metadata': {'f:labels': {'.': {}, 'f:pipelines.kubeflow.org/cache_enabled': {}}}, 'f:spec': {'.': {}, 'f:predictor': {'.': {}, 'f:tensorflow': {'.': {}, 'f:runtimeVersion': {}, 'f:storageUri': {}}}}}, 'manager': 'OpenAPI-Generator', 'operation': 'Update', 'time': '2021-07-01T04:54:05Z'}, {'apiVersion': 'serving.kubeflow.org/v1beta1', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:metadata': {'f:finalizers': {}}, 'f:spec': {'f:predictor': {'f:containers': {}, 'f:tensorflow': {'f:args': {}, 'f:command': {}, 'f:image': {}}}}, 'f:status': {'.': {}, 'f:address': {'.': {}, 'f:url': {}}, 'f:components': {'.': {}, 'f:predictor': {'.': {}, 'f:address': {'.': {}, 'f:url': {}}, 'f:latestCreatedRevision': {}, 'f:latestReadyRevision': {}, 'f:latestRolledoutRevision': {}, 'f:traffic': {}, 'f:url': {}}}, 'f:conditions': {}, 'f:url': {}}}, 'manager': 'manager', 'operation': 'Update', 'time': '2021-07-01T04:54:28Z'}], 'name': 'rflowdemo', 'namespace': 'rflow', 'resourceVersion': '311008', 'uid': '5aca4827-dceb-4263-bd48-9146960fee4c'}, 'spec': {'predictor': {'tensorflow': {'name': 'kfserving-container', 'resources': {'limits': {'cpu': '1', 'memory': '2Gi'}, 'requests': {'cpu': '1', 'memory': '2Gi'}}, 'runtimeVersion': '2.4.0', 'storageUri': 'pvc://tfx-pvc/output/Pusher/pushed_model'}}}, 'status': {'address': {'url': '
> http://rflowdemo.rflow.svc.cluster.local/v1/models/rflowdemo:predict
> '}, 'components': {'predictor': {'address': {'url': 'http://rflowdemo-predictor-default.rflow.svc.cluster.local'}, 'latestCreatedRevision': 'rflowdemo-predictor-default-6ckff', 'latestReadyRevision': 'rflowdemo-predictor-default-6ckff', 'latestRolledoutRevision': 'rflowdemo-predictor-default-6ckff', 'traffic': [{'latestRevision': True, 'percent': 100, 'revisionName': 'rflowdemo-predictor-default-6ckff'}], 'url': 'http://rflowdemo-predictor-default.rflow.example.com'}}, 'conditions': [{'lastTransitionTime': '2021-07-01T04:54:28Z', 'status': 'True', 'type': 'IngressReady'}, {'lastTransitionTime': '2021-07-01T04:54:28Z', 'severity': 'Info', 'status': 'True', 'type': 'PredictorConfigurationReady'}, {'lastTransitionTime': '2021-07-01T04:54:28Z', 'status': 'True', 'type': 'PredictorReady'}, {'lastTransitionTime': '2021-07-01T04:54:27Z', 'severity': 'Info', 'status': 'True', 'type': 'PredictorRouteReady'}, {'lastTransitionTime': '2021-07-01T04:54:28Z', 'status': 'True', 'type': 'Ready'}], 'url': 'http://rflowdemo.rflow.example.com'}}
> http://rflowdemo-predictor-default.rflow.svc.cluster.local
> '}, 'latestCreatedRevision': 'rflowdemo-predictor-default-6ckff', 'latestReadyRevision': 'rflowdemo-predictor-default-6ckff', 'latestRolledoutRevision': 'rflowdemo-predictor-default-6ckff', 'traffic': [{'latestRevision': True, 'percent': 100, 'revisionName': 'rflowdemo-predictor-default-6ckff'}], 'url': 'http://rflowdemo-predictor-default.rflow.example.com'}}, 'conditions': [{'lastTransitionTime': '2021-07-01T04:54:28Z', 'status': 'True', 'type': 'IngressReady'}, {'lastTransitionTime': '2021-07-01T04:54:28Z', 'severity': 'Info', 'status': 'True', 'type': 'PredictorConfigurationReady'}, {'lastTransitionTime': '2021-07-01T04:54:28Z', 'status': 'True', 'type': 'PredictorReady'}, {'lastTransitionTime': '2021-07-01T04:54:27Z', 'severity': 'Info', 'status': 'True', 'type': 'PredictorRouteReady'}, {'lastTransitionTime': '2021-07-01T04:54:28Z', 'status': 'True', 'type': 'Ready'}], 'url': 'http://rflowdemo.rflow.example.com'}}
> http://rflowdemo-predictor-default.rflow.example.com
> '}}, 'conditions': [{'lastTransitionTime': '2021-07-01T04:54:28Z', 'status': 'True', 'type': 'IngressReady'}, {'lastTransitionTime': '2021-07-01T04:54:28Z', 'severity': 'Info', 'status': 'True', 'type': 'PredictorConfigurationReady'}, {'lastTransitionTime': '2021-07-01T04:54:28Z', 'status': 'True', 'type': 'PredictorReady'}, {'lastTransitionTime': '2021-07-01T04:54:27Z', 'severity': 'Info', 'status': 'True', 'type': 'PredictorRouteReady'}, {'lastTransitionTime': '2021-07-01T04:54:28Z', 'status': 'True', 'type': 'Ready'}], 'url': 'http://rflowdemo.rflow.example.com'}}
> http://rflowdemo.rflow.example.com
> '}}
> Model is ready
> http://rflowdemo.rflow.example.com
>  is the Knative domain.
> Sample test commands: 
> curl -v -X GET 
> http://rflowdemo.rflow.example.com
> If the above URL is not accessible, it's recommended to setup Knative with a configured DNS.
> https://knative.dev/docs/install/installing-istio/#configuring-dns
> ```
> 
> We need to delete the inferenceservice running command ` $ kubectl delete inferenceservice -n rflow rflowdemo`
> then run the pipeline again.
> This time it will load and serve the new version of the model.
> 
> ```
> $ kubectl logs rflowdemo-predictor-default-nf72v-deployment-746b56c98c-xtzfc -n rflow storage-initializer
> [I 210701 05:18:31 initializer-entrypoint:13] Initializing, args: src_uri [/mnt/pvc/output/Pusher/pushed_model] dest_path[ [/mnt/models]
> [I 210701 05:18:31 storage:45] Copying contents of /mnt/pvc/output/Pusher/pushed_model to local
> [I 210701 05:18:31 storage:223] Linking: /mnt/pvc/output/Pusher/pushed_model/59 to /mnt/models/59
> [I 210701 05:18:31 storage:223] Linking: /mnt/pvc/output/Pusher/pushed_model/69 to /mnt/models/69
> ```
> 
> It is not a good experience.
> Does any method let KFServing component detect versions of the model using KFP V1 API, so we can run the pipeline without deleting the existing inferenceservice manually?

I found a way to apply Inferenceservice with the newest version of a model every time. That is using kfserving client to manage Inferenceservice. It deletes the Inferenceservice if it is existing, then creates a new Inferenceservice with the newest version of a model. For some people who may care, I post code here.
```python
from kfserving import KFServingClient
from kfserving import constants
from kfserving import V1alpha2EndpointSpec
from kfserving import V1alpha2PredictorSpec
from kfserving import V1alpha2TensorflowSpec
from kfserving import V1alpha2InferenceServiceSpec
from kfserving import V1alpha2InferenceService

kfs_client = KFServingClient()

default_model_spec = V1alpha2EndpointSpec(predictor=V1alpha2PredictorSpec(tensorflow=V1alpha2TensorflowSpec(
    storage_uri='pvc://tfx-pvc/output/Pusher/pushed_model/',
    runtime_version="2.4.0")))

isvc = V1alpha2InferenceService(api_version="serving.kubeflow.org/v1alpha2",
                          kind=constants.KFSERVING_KIND,
                          metadata=client.V1ObjectMeta(name='kfservingdemo', namespace='kubeflow-user-example-com'),
                          spec=V1alpha2InferenceServiceSpec(default=default_model_spec))

try:
    kfs_client.get(name="kfservingdemo")
    kfs_client.delete(name="kfservingdemo")
except:
    print("No existing InferenceService")
kfs_client.create(inferenceservice=isvc, namespace="kubeflow-user-example-com")
```

**Pull request merged**
