### PR TITLE
(ui) Fix status parser bug

### LINKED ISSUE #429: Update UI to support custom task and pipeline run status for tekton 0.19+
/kind feature

**Description:**
Tekton 0.19+ introduced new breaking syntax in its pipelinerun.status. So we need to update the UI after the #428 PR.

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

### PR DESCRIPTION
**Pull request by drewbutlerbb4**
**Which issue is resolved by this Pull Request:** 
Resolves #429 

**Description of your changes:**
Fixes the status being parsed incorrectly due to change in key.

**Environment tested:**

* Python Version (use `python --version`):
* Tekton Version (use `tkn version`):
* Kubernetes Version (use `kubectl version`):
* OS (e.g. from `/etc/os-release`):

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention). 

- [ ] Do you want this pull request (PR) cherry-picked into the current release branch?

    [Learn more about cherry-picking updates into the release branch](https://github.com/kubeflow/pipelines/blob/master/RELEASE.md#cherry-picking-pull-requests-to-release-branch).

### CODE REVIEW

**Comment by drewbutlerbb4** [comment]
Thanks @Tomcli, I made a few more changes

**Comment by animeshsingh** [comment]
lgtm

@Tomcli can you clear this so that we can cut a release today

**Comment by Tomcli** [comment]
thanks @drewbutlerbb4 

/lgtm

**Pull request merged**
