### PR TITLE
replace kfpcompiler to tektoncompiler

### PR DESCRIPTION
**Pull request by kevinyu98**
**Which issue is resolved by this Pull Request:** 
Resolves #

**Description of your changes:**
In the testdata, we are using the tektoncompiler to generate yaml, so replace the condition.py's kfpcompiler to tektoncompiler. Also checked other .py under testdata, seems all are fine.

**Environment tested:**
Iks
* Python Version (use `python --version`):3.7
* Tekton Version (use `tkn version`):
Client version: 0.8.0
Pipeline version: v0.11.3
* Kubernetes Version (use `kubectl version`):
* OS (e.g. from `/etc/os-release`):

### CODE REVIEW

**Comment by kevinyu98** [comment]
@Tomcli

**Comment by kevinyu98** [comment]
@drewbutlerbb4  I just saw your merged pr which you will fix this in your new pr. If it is, I will close this.

**Comment by drewbutlerbb4** [comment]
Yes, this is addressed in #111, thanks to @Tomcli comments

**Comment by kevinyu98** [comment]
close this pr

**Pull request closed without merging**
