### PR TITLE
feat(sdk): extension function `Loop.enumerate()`

### LINKED ISSUE #890: Update SDK with a new extension function ".enumerate()"
/kind feature

**Description:**
Update SDK with a new extension function `.enumerate()`. It returns two PipelineParams that points to the iteration counter and the actual value. Mapping details will be added when the controller implementation is finalized.

Current Loop class extension:
https://github.com/kubeflow/kfp-tekton/blob/master/sdk/python/kfp_tekton/tekton.py#L230

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

### PR DESCRIPTION
**Pull request by yhwang**
Add helper function: `enumerate()` in Loop to
return indices and item. It could be used to get
the current iteration number and item value.

Signed-off-by: Yihong Wang <yh.wang@ibm.com>

**Which issue is resolved by this Pull Request:** 
Resolves #890

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by yhwang** [comment]
@Tomcli @ckadner I added test cases and verified with #898 locally. it works well. If you think of any test cases I can verify or add, please let me know.

**Comment by Tomcli** [comment]
@yhwang so with prashant's current controller it works for you? If so I can merge his PR first.

**Comment by Tomcli** [comment]
maybe we should add a document in another pr to summarize the behavior for the range and enumerate since people could get confused with these terms.

**Comment by yhwang** [comment]
@Tomcli 
> so with prashant's current controller it works for you? If so I can merge his PR first.

yes, I used his PR to verify the SDK change. I also have a test case that uses range + enumerate. but the item element and index are the same value based on his implementation.

> maybe we should add a document in another pr to summarize the behavior for the range and enumerate since people could get confused with these terms.

Yes, good idea. where do you like to document this?  readme of pipeline loop controller?

**Comment by yhwang** [comment]
I also ran the e2e pipeline to verify my change. it used the controller without Prashant's change and no repression issue. https://cloud.ibm.com/devops/pipelines/tekton/f85a45d2-36fc-45fb-a449-b01c13cf5191/runs/c2b2b2d2-aeea-4a16-b448-9fc8722000fa/test/run-go-unittests?env_id=ibm:yp:us-south

**Comment by Tomcli** [comment]
> Yes, good idea. where do you like to document this? readme of pipeline loop controller?

We should have a doc for both controller usage and SDK usage. The controller usage can be part of the pipelineloop readme, the sdk usage can go under the /sdk/FEATURES.md

**Pull request merged**
