### PR TITLE
Update E2E tests to use kfp client (#301)

### LINKED ISSUE #301: Update end to end tests to also test API and client.
/kind feature

**Description:**
Currently, our end to end tests are only testing with pure tekton features. We need to extend our testing to also cover the api and the client. 

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

### PR DESCRIPTION
**Pull request by ckadner**
**Which issue is resolved by this Pull Request:** 
Resolves #301

**Description of your changes:**

* Use `kfp` client to run E2E tests
* Update Tekton server and `tkn` client versions
* Regenerate `pipelinerun` logs
* Delete previous `pipelinerun`s
* Mark tests as `skipped` instead of not generating them

**Additional Information:**

Newly ignored (`@skipped`) test cases:
- `conditions_and_loops.yaml`
- `loop_over_lightweight_output.yaml`
- `loop_static.yaml`
- `parallelfor_item_argument_resolving.yaml`
- `withitem_nested.yaml`
- `withparam_global.yaml`
- `withparam_global_dict.yaml`
- `withparam_output.yaml`
- `withparam_output_dict.yaml`

**Environment tested:**

* Python Version (use `python --version`): `3.9`
* Tekton Version (use `tkn version`): `0.21`
* Kubernetes Version (use `kubectl version`): `1.18`

/cc @Tomcli 
/cc @moficodes

### CODE REVIEW

**Comment by ckadner** [comment]
@Tomcli @fenglixa 

I had to exclude these test cases as they remain in `Running` state as opposed to `Succeeded`:

- `conditions_and_loops.yaml`
- `loop_over_lightweight_output.yaml`
- `loop_static.yaml`
- `parallelfor_item_argument_resolving.yaml`
- `withitem_nested.yaml`
- `withparam_global.yaml`
- `withparam_global_dict.yaml`
- `withparam_output.yaml`
- `withparam_output_dict.yaml`

**Comment by Tomcli** [comment]
> @Tomcli @fenglixa
> 
> I had to exclude these test cases as they remain in `Running` state as opposed to `Succeeded`:
> 
> * `conditions_and_loops.yaml`
> * `loop_over_lightweight_output.yaml`
> * `loop_static.yaml`
> * `parallelfor_item_argument_resolving.yaml`
> * `withitem_nested.yaml`
> * `withparam_global.yaml`
> * `withparam_global_dict.yaml`
> * `withparam_output.yaml`
> * `withparam_output_dict.yaml`

For loops we will need to enable custom task and deploy the loop controller. Also we have few new crds for running loop examples. You can checkout the new deployment at https://github.com/kubeflow/kfp-tekton/pull/479

**Comment by ckadner** [comment]
> For loops we will need to enable custom task and deploy the loop controller. 

@Tomcli -- I did enable custom tasks, deployed the CRDs and the pipelineruns produce log output. But the pipelineruns never go from `Running` to `Succedded` state

**Comment by ckadner** [comment]
> Some of these tests will split the new crd loops (like xxx.cr1.yaml) that you have to deploy it before running the pipelines. 

Yup. I had also deployed all of the `*_cr1.yaml` files prior to running the tests:

```Bash
for f in sdk/python/tests/compiler/testdata/*_cr*.yaml; do \
    kubectl apply -f "${f}" -n kubeflow
done
```

> We are waiting for some tekton api changes in order to put these into one yaml.

I will leave them in the ignored tests list for now

**Comment by ckadner** [comment]
@Tomcli -- can we merge this PR so we can get back to using these E2E tests for the open and upcoming PRs with functional changes to the SDK?

**Comment by Tomcli** [comment]
thanks @ckadner
/lgtm
/approve

**Pull request merged**
