### PR TITLE
fix(backend): cover nil status race condition from Tekton

### PR DESCRIPTION
**Pull request by Tomcli**
**Which issue is resolved by this Pull Request:** 
Resolves #

**Description of your changes:**
Occasionally Tekton may store the pipelineRun to etcd before populating the status field, which it will create a nil pointer panic to the persistent agent. Thus, adding a defer fallback to catch this edge case.

**Environment tested:**

* Python Version (use `python --version`):
* Tekton Version (use `tkn version`): 1.14
* Kubernetes Version (use `kubectl version`): 1.16
* OS (e.g. from `/etc/os-release`):

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention). 

   PR titles examples:
    * `fix(frontend): fixes empty page. Fixes #1234`
       Use `fix` to indicate that this PR fixes a bug.
    * `feat(backend): configurable service account. Fixes #1234, fixes #1235`
       Use `feat` to indicate that this PR adds a new feature. 
    * `chore: set up changelog generation tools`
       Use `chore` to indicate that this PR makes some changes that users don't need to know.
    * `test: fix CI failure. Part of #1234`
        Use `part of` to indicate that a PR is working on an issue, but shouldn't close the issue when merged.

- [ ] Do you want this pull request (PR) cherry-picked into the current release branch?
    
    If yes, use one of the following options:
  
    * **(Recommended.)** Ask the PR approver to add the `cherrypick-approved` label to this PR. The release manager adds this PR to the release branch in a batch update.
    *  After this PR is merged, create a cherry-pick PR to add these changes to the release branch. (For more information about creating a cherry-pick PR, see the [Kubeflow Pipelines release guide](https://github.com/kubeflow/pipelines/blob/master/RELEASE.md#option--git-cherry-pick).)

### CODE REVIEW

**Comment by Tomcli** [comment]
@adrian555 I just updated the persistent agent image with the this fix, let me know if you still see the nil pointer error.

**Comment by drewbutlerbb4** [comment]
/lgtm
Haven't been able to reproduce past issue in the testing of 5 pipelines across 250+ runs. The persistent agent never crashed throughout the 250+ runs.

**Comment by Tomcli** [comment]
@drewbutlerbb4 I fixed the conflicts with the upstream code. Does this look good to you?

**Comment by drewbutlerbb4** [comment]
Yes, thanks @Tomcli 
/lgtm

**Pull request merged**
