### PR TITLE
Sanitize Tekton result parameters when passing to custom task inputs

### LINKED ISSUE #577: Tekton variables for custom task results are not sanitized when using it in condition
/kind bug

**What steps did you take and what happened:**
When defining custom task output as `return_value` (with underscore), we need to sanitize it in to hyphen `-` order to let the Tekton controller understands what to do. These variables are already sanitized for regular tasks I/O, but the below edge case wasn't sanitized within custom task.
```
- name: condition-cel
      params:
      - name: status
        value: $(tasks.node-run-bash-script.results.return_value) == 0
```

We need to update the compiler to cover this edge case.

**What did you expect to happen:**

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

* Python Version (use `python --version`):
* SDK Version: 
* Tekton Version (use `tkn version`):
* Kubernetes Version (use `kubectl version`):
* OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by Tomcli**
**Which issue is resolved by this Pull Request:** 
Resolves #577 

**Description of your changes:**
When passing the Tekton result parameters with underscore keys to custom tasks, the Tekton variables are not properly sanitized. Thus, this PR fix the sanitization for custom task inputs.

**Environment tested:**

* Python Version (use `python --version`):
* Tekton Version (use `tkn version`):
* Kubernetes Version (use `kubectl version`):
* OS (e.g. from `/etc/os-release`):

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention). 

- [ ] Do you want this pull request (PR) cherry-picked into the current release branch?

    [Learn more about cherry-picking updates into the release branch](https://github.com/kubeflow/pipelines/blob/master/RELEASE.md#cherry-picking-pull-requests-to-release-branch).

### CODE REVIEW

**Comment by Tomcli** [comment]
cc @Udiknedormin

**Review by ckadner — APPROVED** [review]
/lgtm

**Comment by ckadner** [comment]
Thanks @Tommy

**Pull request merged**
