### PR TITLE
Kfp 1.8.0 api and frontend rebase

### PR DESCRIPTION
**Pull request by Tomcli**
**Which issue is resolved by this Pull Request:** 
Resolves #

**Description of your changes:**

**Environment tested:**

* Python Version (use `python --version`):
* Tekton Version (use `tkn version`):
* Kubernetes Version (use `kubectl version`):
* OS (e.g. from `/etc/os-release`):

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by Tomcli** [comment]
ci testing https://cloud.ibm.com/devops/pipelines/tekton/f85a45d2-36fc-45fb-a449-b01c13cf5191/runs/669700af-19e9-429e-8531-b30d216ba3b4/test/run-go-unittests?env_id=ibm:yp:us-south

**Comment by Tomcli** [comment]
@ckadner do you know the command to change all commits to the bot? I think the instructions only updated the latest commit. I need to do a rebase commit?

**Comment by ckadner** [comment]
> @ckadner do you know the command to change all commits to the bot? I think the instructions only updated the latest commit. I need to do a rebase commit?

https://github.com/kubeflow/kfp-tekton/blob/master/guides/kfp-rebase-guide.md#how-to-accept-a-pr-on-the-rebase-branch

```Bash
# Do NOT keep commits with a non-bot author!
# unstage last commit, or more (n number of commits) "HEAD~n" 
git reset HEAD~1
```

Modify the command to:

```Bash
git reset HEAD~2
```

... to unstage the previous two commits and then recommit in a single commit:

```Bash
# now re-commit staged files as "kfp-tekton-bot" user
git commit -m "< message >" --author="${GIT_COMMITTER_NAME} <${GIT_COMMITTER_EMAIL}>"

# push the branch with force (-f) since we are rewriting commit history
git push -f
```

**Comment by Tomcli** [comment]
thanks @ckadner for the pointer

**Comment by Tomcli** [comment]
I will add the sdk update after this, try to separate them into two PR so we can backtrack it.

**Review by yhwang — APPROVED** [review]
/lgtm

**Pull request merged**
